"""Purpose batch0 HTTP/FIFO -> original PCL ordinal and full49 lineage."""
import copy,hashlib,json,re,struct
from pathlib import Path
from full_cache_shared_history_v2 import require,digest

PROTOCOL=('READY','ERR','RESUME ','REUSED ','PP ','T ','LP ','DONE ')

def request_view(events,begin,end,expected):
 """A NEW derived view of original records, never a saved raw proof rewrite."""
 require(type(expected)is dict and set(expected)=={'ids','fresh','pin','expected_reused'} and type(expected['fresh'])is int and expected['fresh'] in (0,1) and (expected['pin'] is None or type(expected['pin'])is int) and type(expected['expected_reused'])is int,'Explicit preregistered serial policy required')
 ids=expected['ids'];digest(ids);require(begin['kind']=='engine_begin' and end['kind']=='engine_end' and type(begin['call'])is int and begin['call']==end['call'] and type(begin['engine_pid'])is int and begin['engine_pid']>0 and begin['engine_pid']==end['engine_pid'] and type(begin['engine_generation'])is int and begin['engine_generation']>0 and begin['engine_generation']==end['engine_generation'],'Actual same-incarnation HTTP FIFO owner required')
 require(begin['sequence']<end['sequence'] and begin['submitted_ids']==ids and begin['submitted_ids_sha256']==digest(ids) and begin['rendered_matches_submitted'] is True and begin['rendered_prompt']['ids']==ids and type(begin['max_new'])is int and begin['max_new']==1 and begin['embeddings'] is None,'Actual original frontend accepted input/GEN1 shape differs')
 require(end['error'] is None and end['cancelled'] is False and len(end['generated_ids'])==1 and end['generated_ids_sha256']==digest(end['generated_ids']),'Actual own complete one-token HTTP result required')
 require(all(type(e['sequence'])is int and (i==0 or e['sequence']>events[i-1]['sequence']) for i,e in enumerate(events)),'Original unique source sequence order required')
 require(not any(e['kind']=='engine_begin' and e['call']!=begin['call'] for e in events),'Batch0 source interval must have one actual FIFO request')
 sends=[e for e in events if e['kind']=='native_send'];require(not any(e['kind'] in ('session_begin','session_end','fullcache_control_send') for e in events),'Request FIFO interval cannot borrow persisted/control activity');require(len(sends)==1 and sends[0]['call']==begin['call'] and sends[0]['engine_pid']==begin['engine_pid'] and begin['sequence']<sends[0]['sequence']<end['sequence'],'Actual sole native GEN/HTTP send association differs')
 send=sends[0];words=send['line'].split();keys=dict(re.findall(r'(\w+)=([^ ]+)',send['line']));require(words[:2]==['GEN','1'] and [int(t) for t in words[-1].split(',')]==ids and 'rid' not in keys and 'slotgen' not in keys,'Batch0 uses actual bare GEN, never forged strict-batch RID')
 require(keys.get('fresh')==str(expected['fresh']) and ('pin' not in keys if expected['pin'] is None else keys.get('pin')==str(expected['pin'])),'Actual serial fresh/PIN policy differs')
 received=[e for e in events if e['kind']=='native_receive' and e['sequence']>send['sequence']];require(received and all(e['engine_pid']==begin['engine_pid'] for e in received),'Actual same-process original raw receive roster required');lines=[e['line'] for e in received];require(not any(line.startswith(('ERR','FATAL','SERR ')) for line in lines),'Actual native error cannot be ignored beside valid output');done=[e for e in received if e['line'].startswith('DONE ')];tokens=[e for e in received if e['line'].startswith('T ')];require(len(done)==len(tokens)==1 and send['sequence']<tokens[0]['sequence']<done[0]['sequence']<end['sequence'] and int(tokens[0]['line'].split()[1])==end['generated_ids'][0],'Original native token/DONE must match actual HTTP yield')
 parts=done[0]['line'].split();require(len(parts)>=15 and int(parts[1])==1 and int(parts[2])==len(ids) and parts[5] in ('length','stop') and int(parts[8])==expected['expected_reused'] and int(parts[14])==len(ids)-expected['expected_reused'],'Actual declared prompt/read/reuse counters differ')
 pcl=[json.loads(line[4:]) for line in lines if line.startswith('PCL ')];starts=[r for r in pcl if r['event']=='begin'];ends=[r for r in pcl if r['event']=='committed_live'];require(len(starts)==len(ends)==1,'Actual unique PCL begin/commit required');owner=starts[0];commit=ends[0];require(type(owner['request'])is int and owner['request']>0 and type(owner['pid'])is int and owner['pid']==begin['engine_pid'] and owner['tokens']==len(ids) and owner['input_sha256_le32']==digest(ids) and all(type(r['pid'])is int and type(r['request'])is int and r['pid']==owner['pid'] and r['request']==owner['request'] for r in pcl),'Actual native PCL ordinal/input owner differs')
 require(digest(commit['ids'])==digest(ids) and commit['ids']==ids and type(commit['tokens'])is int and commit['tokens']==len(ids) and commit['sha256_le32']==digest(ids) and commit['ids_truncated'] is False and commit['phase']=='complete','Saved serial state must be actual consumed GEN1 prefix, not emitted-but-unconsumed token')
 view={'ids':copy.deepcopy(ids),'fresh':expected['fresh'],'pin':expected['pin'],'command':send['line'],'output_ids':list(end['generated_ids']),'done':done[0]['line'],'stderr':[line for line in lines if not line.startswith(PROTOCOL)],'cancel_requested':None,'stop_sent':False}
 return view,{'actual_native_PCL_pid':owner['pid'],'actual_native_PCL_request_ordinal':owner['request'],'actual_HTTP_call':begin['call'],'actual_engine_generation':begin['engine_generation'],'native_send_sequence':send['sequence'],'native_terminal_sequence':done[0]['sequence'],'HTTP_begin_sequence':begin['sequence'],'HTTP_end_sequence':end['sequence'],'strict_batch_RID_claimed':False,'source_record_SHA256':hashlib.sha256(json.dumps(events,sort_keys=True,separators=(',',':'),ensure_ascii=True).encode()).hexdigest(),'derived_view_sha256':hashlib.sha256(json.dumps(view,sort_keys=True,separators=(',',':'),ensure_ascii=True).encode()).hexdigest(),'original_records_rewritten':False,'actual_full49_still_required':True}

def full49(events,begin,end,expected,capture_root,stage_ranges):
 from serial_prefix_qualification_v6 import extract
 view,binding=request_view(events,begin,end,expected);original=copy.deepcopy(view);meta=extract(view,Path(capture_root),True,True,stage_ranges);vectors={str(int(r['layer'])):r for r in meta['residuals']};require(len(meta['logits'])==1,'Actual full vocabulary head missing');vectors['-1']=meta['logits'][0];require(set(vectors)=={str(k) for k in range(-1,48)},'Actual original serial full49 missing')
 for row in vectors.values():
  p=Path(row['path']);before=p.stat();raw=p.read_bytes();require(len(raw)==int(row['bytes']) and hashlib.sha256(raw).hexdigest()==row['sha256'] and p.read_bytes()==raw and p.stat()==before,'Actual consumed raw field changed during full49 admission')
 vectors={key:{'path':row['path'],'bytes':int(row['bytes']),'sha256':row['sha256'],'position':int(row['pos']),'token':int(row['token']),'source_native_descriptor':copy.deepcopy(row)} for key,row in vectors.items()}
 require(meta['lifecycle']['begin']['pid']==binding['actual_native_PCL_pid'] and meta['lifecycle']['begin']['request']==binding['actual_native_PCL_request_ordinal'],'Public frozen PCL validator disagrees with actual HTTP source owner')
 return {'source_lineage':binding,'original_derived_view':original,'derived_after_frozen_validator':view,'actual_frozen_PCL_numeric_admission':meta,'vectors':vectors,'input_ids':list(expected['ids']),'fresh49_control_and_current_parent_still_required':True,'persisted_restore_or_full_cache_qualified':False}
