// Diagnostic interposer for unchanged Half37 ELF; actual extracted LevelZero ABI.
#include <level_zero/ze_api.h>
#include <level_zero/ze_ddi.h>
#include <atomic>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <dlfcn.h>
#include <fcntl.h>
#include <mutex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>
#include <unistd.h>
#include <sys/stat.h>
namespace {
constexpr size_t MAX_BYTES=16u<<20,MAX_TOTAL=64u<<20,MAX_EVENTS=8192,MAX_OBJECTS=512;
std::atomic<bool>capture_failed{false};
bool enabled(){static bool value=std::getenv("HALF37_NATIVE_BINARY_DIR")!=nullptr;return value;}
std::string address(const void*p){char b[64];std::snprintf(b,sizeof(b),"%p",p);return std::string(b);}
std::string hex(const uint8_t*p,size_t n){std::string out;for(size_t i=0;i<n;++i){char b[3];std::snprintf(b,3,"%02x",p[i]);out+=b;}return out;}
std::string quoted(const char* text){std::string out="\"";if(text)for(size_t i=0;text[i]&&i<4096;++i){unsigned char c=text[i];if(c=='"'||c=='\\'){out+='\\';out+=c;}else if(c<32||c>126){char b[7];std::snprintf(b,7,"\\u%04x",c);out+=b;}else out+=c;}return out+'"';}
struct Module{uint64_t id=0;std::string input,native;};struct Kernel{uint64_t id=0,module=0;std::string name;};struct List{uint64_t id=0;bool immediate=false;std::vector<Kernel>kernels;};
struct State{std::mutex lock;int dir=-1;FILE*log=nullptr;size_t events=0,bytes=0;uint64_t sequence=0,id=0;bool failed=false,closed=false;pid_t owner=getpid();std::unordered_map<void*,Module>modules;std::unordered_map<void*,Kernel>kernels;std::unordered_map<void*,List>lists;
 State(){const char*p=std::getenv("HALF37_NATIVE_BINARY_DIR");char actual[4096];if(!p||p[0]!='/'||!realpath(p,actual)||std::strcmp(p,actual)){failed=true;return;}dir=open(p,O_DIRECTORY|O_RDONLY|O_NOFOLLOW|O_CLOEXEC);if(dir<0){failed=true;return;}int fd=openat(dir,"events.jsonl",O_CREAT|O_EXCL|O_WRONLY|O_NOFOLLOW|O_CLOEXEC,0600);if(fd>=0)log=fdopen(fd,"w");if(!log){if(fd>=0)close(fd);failed=true;}}
 void event(const std::string&body){if(closed)return;if(owner!=getpid()){capture_failed.store(true);return;}if(!log||events++>=MAX_EVENTS){failed=true;return;}std::fprintf(log,"{\"sequence\":%llu,\"pid\":%d,%s}\n",(unsigned long long)++sequence,(int)getpid(),body.c_str());if(std::fflush(log)||std::ferror(log))failed=true;}
 void error(const char*message){failed=true;event("\"event\":\"error\",\"message\":"+quoted(message));}
 std::string dump(uint64_t object,const char*role,const void*data,size_t size){if(!data||!size||size>MAX_BYTES||size>MAX_TOTAL-bytes){error("binary bound exceeded");return {};}std::string name="module-"+std::to_string(object)+"-"+role+".bin";int fd=openat(dir,name.c_str(),O_CREAT|O_EXCL|O_WRONLY|O_NOFOLLOW|O_CLOEXEC,0600);if(fd<0){error("exclusive binary output failed");return {};}size_t written=0;while(written<size){ssize_t n=write(fd,(const char*)data+written,size-written);if(n<=0)break;written+=(size_t)n;}int rc=close(fd);if(written!=size||rc){error("complete binary write/close failed");return {};}bytes+=size;return name;}
 void finish(){if(closed)return;closed=true;if(log){std::fprintf(log,"{\"sequence\":%llu,\"pid\":%d,\"event\":\"terminal\",\"failed\":%s,\"events\":%zu,\"binary_bytes\":%zu}\n",(unsigned long long)++sequence,(int)getpid(),(failed||capture_failed.load())?"true":"false",events,bytes);int flushed=std::fflush(log),bad=std::ferror(log),closed_rc=std::fclose(log);if(flushed||bad||closed_rc){capture_failed.store(true);std::fputs("HALF37_INTERPOSER terminal failure\n",stderr);}log=nullptr;}if(dir>=0){close(dir);dir=-1;}}
};State&state(){static State*value=new State;return *value;}
__attribute__((destructor))void finish_capture() noexcept {if(enabled())try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.finish();}catch(...){capture_failed.store(true);std::fputs("HALF37_INTERPOSER terminal failure\n",stderr);}}
template<class F> F original(const char*name,std::atomic<F>&slot){F value=slot.load();if(!value){value=reinterpret_cast<F>(dlsym(RTLD_NEXT,name));slot.store(value);}return value;}
template<class F> void capture(std::atomic<F>&slot,F value,F wrapper){if(value&&value!=wrapper)slot.store(value);}
#define PTR(NAME,TYPE) std::atomic<TYPE> NAME{nullptr}
PTR(moduleCreate,ze_pfnModuleCreate_t);PTR(moduleDestroy,ze_pfnModuleDestroy_t);PTR(nativeBinary,ze_pfnModuleGetNativeBinary_t);PTR(kernelCreate,ze_pfnKernelCreate_t);PTR(kernelDestroy,ze_pfnKernelDestroy_t);PTR(listCreate,ze_pfnCommandListCreate_t);PTR(listImmediate,ze_pfnCommandListCreateImmediate_t);PTR(listDestroy,ze_pfnCommandListDestroy_t);PTR(listReset,ze_pfnCommandListReset_t);PTR(launch,ze_pfnCommandListAppendLaunchKernel_t);PTR(execute,ze_pfnCommandQueueExecuteCommandLists_t);PTR(cloneFn,ze_pfnCommandListCreateCloneExp_t);PTR(appendLists,ze_pfnCommandListImmediateAppendCommandListsExp_t);
void submitted(State&s,ze_command_list_handle_t h,const char*via){auto it=s.lists.find(h);if(it==s.lists.end()){s.error("unobserved submitted command list");return;}for(const auto&k:it->second.kernels)s.event("\"event\":\"submitted\",\"via\":"+quoted(via)+",\"list\":"+std::to_string(it->second.id)+",\"kernel\":"+std::to_string(k.id)+",\"module\":"+std::to_string(k.module)+",\"name\":"+quoted(k.name.c_str()));}
}
extern "C" ze_result_t ZE_APICALL zeModuleCreate(ze_context_handle_t c,ze_device_handle_t d,const ze_module_desc_t*desc,ze_module_handle_t*out,ze_module_build_log_handle_t*log){auto f=original("zeModuleCreate",moduleCreate);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(c,d,desc,out,log);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(s.modules.size()>=MAX_OBJECTS){s.error("module bound exceeded");return rc;}Module m;m.id=++s.id;if(desc){m.input=s.dump(m.id,"input",desc->pInputModule,desc->inputSize);}auto native=original("zeModuleGetNativeBinary",nativeBinary);size_t bytes=0;ze_result_t a=native?native(*out,&bytes,nullptr):ZE_RESULT_ERROR_UNINITIALIZED,b=a;if(a==ZE_RESULT_SUCCESS&&bytes&&bytes<=MAX_BYTES){std::vector<uint8_t>raw(bytes);b=native(*out,&bytes,raw.data());if(b==ZE_RESULT_SUCCESS&&bytes<=raw.size())m.native=s.dump(m.id,"native",raw.data(),bytes);}if(m.native.empty())s.error("actual native binary query missing");using Props=ze_result_t(ZE_APICALL*)(ze_device_handle_t,ze_device_properties_t*);auto props=reinterpret_cast<Props>(dlsym(RTLD_NEXT,"zeDeviceGetProperties"));ze_device_properties_t properties{};properties.stype=ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES;auto prc=props?props(d,&properties):ZE_RESULT_ERROR_UNINITIALIZED;s.modules[*out]=m;s.event("\"event\":\"module\",\"context\":"+quoted(address(c).c_str())+",\"device\":"+quoted(address(d).c_str())+",\"device_properties_rc\":"+std::to_string((uint32_t)prc)+",\"device_id\":"+std::to_string(properties.deviceId)+",\"vendor_id\":"+std::to_string(properties.vendorId)+",\"device_uuid\":"+quoted(hex(properties.uuid.id,ZE_MAX_DEVICE_UUID_SIZE).c_str())+",\"device_name\":"+quoted(properties.name)+",\"id\":"+std::to_string(m.id)+",\"format\":"+std::to_string(desc?(int)desc->format:-1)+",\"pnext_present\":"+(desc&&desc->pNext?"true":"false")+",\"constants_present\":"+(desc&&desc->pConstants?"true":"false")+",\"input\":"+quoted(m.input.c_str())+",\"native\":"+quoted(m.native.c_str())+",\"build_flags\":"+quoted(desc?desc->pBuildFlags:nullptr));}catch(...){capture_failed.store(true);std::fputs("HALF37_INTERPOSER capture exception\n",stderr);}return rc;}
extern "C" ze_result_t ZE_APICALL zeModuleDestroy(ze_module_handle_t h){auto f=original("zeModuleDestroy",moduleDestroy);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.modules.erase(h);}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeKernelCreate(ze_module_handle_t m,const ze_kernel_desc_t*d,ze_kernel_handle_t*out){auto f=original("zeKernelCreate",kernelCreate);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(m,d,out);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(s.kernels.size()>=MAX_OBJECTS){s.error("kernel bound exceeded");return rc;}auto it=s.modules.find(m);if(it==s.modules.end()){s.error("kernel module creation unobserved");return rc;}Kernel k{++s.id,it->second.id,d&&d->pKernelName?d->pKernelName:""};s.kernels[*out]=k;s.event("\"event\":\"kernel\",\"id\":"+std::to_string(k.id)+",\"module\":"+std::to_string(k.module)+",\"name\":"+quoted(k.name.c_str()));}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeKernelDestroy(ze_kernel_handle_t h){auto f=original("zeKernelDestroy",kernelDestroy);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.kernels.erase(h);}catch(...){capture_failed.store(true);}return rc;}
#define LIST_CREATE(NAME,SLOT,DESC,IMMEDIATE) extern "C" ze_result_t ZE_APICALL NAME(ze_context_handle_t c,ze_device_handle_t d,const DESC*x,ze_command_list_handle_t*out){auto f=original(#NAME,SLOT);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(c,d,x,out);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(s.lists.size()>=MAX_OBJECTS){s.error("list bound exceeded");return rc;}s.lists[*out]=List{++s.id,IMMEDIATE,{}};}catch(...){capture_failed.store(true);}return rc;}
LIST_CREATE(zeCommandListCreate,listCreate,ze_command_list_desc_t,false)
LIST_CREATE(zeCommandListCreateImmediate,listImmediate,ze_command_queue_desc_t,true)
extern "C" ze_result_t ZE_APICALL zeCommandListDestroy(ze_command_list_handle_t h){auto f=original("zeCommandListDestroy",listDestroy);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.lists.erase(h);}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListReset(ze_command_list_handle_t h){auto f=original("zeCommandListReset",listReset);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto it=s.lists.find(h);if(it!=s.lists.end())it->second.kernels.clear();}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListAppendLaunchKernel(ze_command_list_handle_t h,ze_kernel_handle_t k,const ze_group_count_t*x,ze_event_handle_t signal,uint32_t n,ze_event_handle_t*wait){auto f=original("zeCommandListAppendLaunchKernel",launch);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,k,x,signal,n,wait);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto a=s.lists.find(h);auto b=s.kernels.find(k);if(a==s.lists.end()||b==s.kernels.end())s.error("launch owner unobserved");else if(a->second.kernels.size()>=MAX_OBJECTS)s.error("list kernel bound exceeded");else{a->second.kernels.push_back(b->second);s.event("\"event\":\"append\",\"kernel\":"+std::to_string(b->second.id)+",\"list\":"+std::to_string(a->second.id));if(a->second.immediate){submitted(s,h,"immediate");a->second.kernels.clear();}}}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandQueueExecuteCommandLists(ze_command_queue_handle_t q,uint32_t n,ze_command_list_handle_t*lists,ze_fence_handle_t fence){auto f=original("zeCommandQueueExecuteCommandLists",execute);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(q,n,lists,fence);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(n>MAX_OBJECTS)s.error("submitted list count exceeds bound");else for(uint32_t i=0;i<n;++i)submitted(s,lists[i],"queue");}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListCreateCloneExp(ze_command_list_handle_t h,ze_command_list_handle_t*out){auto f=original("zeCommandListCreateCloneExp",cloneFn);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,out);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto it=s.lists.find(h);if(it==s.lists.end()||s.lists.size()>=MAX_OBJECTS)s.error("clone source owner missing/bounded");else{List copy=it->second;copy.id=++s.id;s.lists[*out]=copy;}}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListImmediateAppendCommandListsExp(ze_command_list_handle_t h,uint32_t n,ze_command_list_handle_t*lists,ze_event_handle_t signal,uint32_t waits,ze_event_handle_t*events){auto f=original("zeCommandListImmediateAppendCommandListsExp",appendLists);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,n,lists,signal,waits,events);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(n>MAX_OBJECTS)s.error("graph list count exceeds bound");else for(uint32_t i=0;i<n;++i)submitted(s,lists[i],"immediate-graph");}catch(...){capture_failed.store(true);}return rc;}
#define TABLE(NAME,TYPE,BODY) extern "C" ze_result_t ZE_APICALL NAME(ze_api_version_t version,TYPE*table){using F=ze_result_t(ZE_APICALL*)(ze_api_version_t,TYPE*);static std::atomic<F>fn{nullptr};auto f=original(#NAME,fn);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(version,table);if(enabled()&&rc==ZE_RESULT_SUCCESS&&table)try{BODY;auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.event("\"event\":\"proc_table\",\"name\":"+quoted(#NAME)+",\"version\":"+std::to_string((uint32_t)version));}catch(...){capture_failed.store(true);}return rc;}
#define HOOK(FIELD,SLOT,WRAPPER) if(table->FIELD){capture(SLOT,table->FIELD,&WRAPPER);table->FIELD=&WRAPPER;}
TABLE(zeGetModuleProcAddrTable,ze_module_dditable_t,HOOK(pfnCreate,moduleCreate,zeModuleCreate);HOOK(pfnDestroy,moduleDestroy,zeModuleDestroy);if(table->pfnGetNativeBinary)nativeBinary.store(table->pfnGetNativeBinary))
TABLE(zeGetKernelProcAddrTable,ze_kernel_dditable_t,HOOK(pfnCreate,kernelCreate,zeKernelCreate);HOOK(pfnDestroy,kernelDestroy,zeKernelDestroy))
TABLE(zeGetCommandListProcAddrTable,ze_command_list_dditable_t,HOOK(pfnCreate,listCreate,zeCommandListCreate);HOOK(pfnCreateImmediate,listImmediate,zeCommandListCreateImmediate);HOOK(pfnDestroy,listDestroy,zeCommandListDestroy);HOOK(pfnReset,listReset,zeCommandListReset);HOOK(pfnAppendLaunchKernel,launch,zeCommandListAppendLaunchKernel))
TABLE(zeGetCommandQueueProcAddrTable,ze_command_queue_dditable_t,HOOK(pfnExecuteCommandLists,execute,zeCommandQueueExecuteCommandLists))
TABLE(zeGetCommandListExpProcAddrTable,ze_command_list_exp_dditable_t,HOOK(pfnCreateCloneExp,cloneFn,zeCommandListCreateCloneExp);HOOK(pfnImmediateAppendCommandListsExp,appendLists,zeCommandListImmediateAppendCommandListsExp))
