// Exercise both exported and actual DDI-pointer dispatch without GPU libraries.
#include <level_zero/ze_api.h>
#include <level_zero/ze_ddi.h>
#include <cstdlib>
#include <cstdio>
#include <cstdint>
#include <dlfcn.h>
#define CHECK(X) if((X)!=ZE_RESULT_SUCCESS)return 2
int main(){if(std::getenv("HALF37_FAKE_TWO_DOMAINS")){
 void*a=dlopen("/out/libhalf37_fake_driver.so",RTLD_NOW|RTLD_LOCAL),*b=dlopen("/out/libhalf37_fake_driver_b.so",RTLD_NOW|RTLD_LOCAL);if(!a||!b)return 10;
 auto ga=reinterpret_cast<ze_pfnGetModuleProcAddrTable_t>(dlsym(a,"zeGetModuleProcAddrTable"));auto gb=reinterpret_cast<ze_pfnGetModuleProcAddrTable_t>(dlsym(b,"zeGetModuleProcAddrTable"));auto ka=reinterpret_cast<ze_pfnGetKernelProcAddrTable_t>(dlsym(a,"zeGetKernelProcAddrTable"));auto kb=reinterpret_cast<ze_pfnGetKernelProcAddrTable_t>(dlsym(b,"zeGetKernelProcAddrTable"));
 if(!ga||!gb||!ka||!kb)return 11;ze_module_dditable_t ma{},mb{};ze_kernel_dditable_t ta{},tb{};CHECK(ga(ZE_API_VERSION_CURRENT,&ma));CHECK(ka(ZE_API_VERSION_CURRENT,&ta));CHECK(gb(ZE_API_VERSION_CURRENT,&mb));CHECK(kb(ZE_API_VERSION_CURRENT,&tb));
 uint8_t input[8]={3,2,35,7,0,0,0,0};ze_module_desc_t md{};md.stype=ZE_STRUCTURE_TYPE_MODULE_DESC;md.format=ZE_MODULE_FORMAT_IL_SPIRV;md.inputSize=8;md.pInputModule=input;md.pBuildFlags="CPU_TWO_DOMAINS";ze_module_handle_t ha{},hb{};auto c=(ze_context_handle_t)(uintptr_t)1;auto d=(ze_device_handle_t)(uintptr_t)2;
 // Invoke saved A after binding B; wrong-domain forwarding must fail.
 CHECK(ma.pfnCreate(c,d,&md,&ha,nullptr));CHECK(mb.pfnCreate(c,d,&md,&hb,nullptr));if((uintptr_t)ha!=0x10100||(uintptr_t)hb!=0x20100)return 12;
 uint8_t raw[64];size_t n=64;CHECK(ma.pfnGetNativeBinary(ha,&n,raw));if(raw[4]!=1)return 13;n=64;CHECK(mb.pfnGetNativeBinary(hb,&n,raw));if(raw[4]!=2)return 14;
 ze_kernel_desc_t kd{};kd.stype=ZE_STRUCTURE_TYPE_KERNEL_DESC;kd.pKernelName="CPU_DOMAIN";ze_kernel_handle_t xa{},xb{};CHECK(ta.pfnCreate(ha,&kd,&xa));CHECK(tb.pfnCreate(hb,&kd,&xb));CHECK(ta.pfnDestroy(xa));CHECK(tb.pfnDestroy(xb));CHECK(ma.pfnDestroy(ha));CHECK(mb.pfnDestroy(hb));std::puts("CPU_TWO_DOMAIN_SAVED_ENDPOINT_PASS actual_GPU_touch=0");}
void*driver=dlopen("/out/libhalf37_fake_driver.so",RTLD_NOW|RTLD_LOCAL);if(!driver)return 4;auto moduleGetter=reinterpret_cast<ze_pfnGetModuleProcAddrTable_t>(dlsym(driver,"zeGetModuleProcAddrTable"));auto kernelGetter=reinterpret_cast<ze_pfnGetKernelProcAddrTable_t>(dlsym(driver,"zeGetKernelProcAddrTable"));auto listGetter=reinterpret_cast<ze_pfnGetCommandListProcAddrTable_t>(dlsym(driver,"zeGetCommandListProcAddrTable"));auto queueGetter=reinterpret_cast<ze_pfnGetCommandQueueProcAddrTable_t>(dlsym(driver,"zeGetCommandQueueProcAddrTable"));auto expGetter=reinterpret_cast<ze_pfnGetCommandListExpProcAddrTable_t>(dlsym(driver,"zeGetCommandListExpProcAddrTable"));if(!moduleGetter||!kernelGetter||!listGetter||!queueGetter||!expGetter)return 5;ze_module_dditable_t m{};ze_kernel_dditable_t k{};ze_command_list_dditable_t l{};ze_command_queue_dditable_t q{};ze_command_list_exp_dditable_t e{};CHECK(moduleGetter(ZE_API_VERSION_CURRENT,&m));CHECK(kernelGetter(ZE_API_VERSION_CURRENT,&k));CHECK(listGetter(ZE_API_VERSION_CURRENT,&l));CHECK(queueGetter(ZE_API_VERSION_CURRENT,&q));CHECK(expGetter(ZE_API_VERSION_CURRENT,&e));if(std::getenv("HALF37_FAKE_NULL_EXP")&&(e.pfnCreateCloneExp||e.pfnImmediateAppendCommandListsExp))return 3;
 auto c=(ze_context_handle_t)(uintptr_t)1;auto d=(ze_device_handle_t)(uintptr_t)2;ze_command_list_handle_t regular{},immediate{};ze_command_list_desc_t ld{};ze_command_queue_desc_t qd{};CHECK(l.pfnCreate(c,d,&ld,&regular));CHECK(l.pfnCreateImmediate(c,d,&qd,&immediate));const char*names[]={"_ZTS16Half37Expression","_ZTS11Half37Store","_ZTS10Half37Load"};ze_group_count_t groups{1,1,1};uint8_t input[8]={3,2,35,7,0,0,0,0};
 for(int i=0;i<3;++i){ze_module_desc_t md{};md.stype=ZE_STRUCTURE_TYPE_MODULE_DESC;md.format=ZE_MODULE_FORMAT_IL_SPIRV;md.inputSize=8;md.pInputModule=input;md.pBuildFlags="CPU_SYNTHETIC";ze_module_handle_t module{};CHECK(i?m.pfnCreate(c,d,&md,&module,nullptr):zeModuleCreate(c,d,&md,&module,nullptr));ze_kernel_desc_t kd{};kd.stype=ZE_STRUCTURE_TYPE_KERNEL_DESC;kd.pKernelName=names[i];ze_kernel_handle_t kernel{};CHECK(k.pfnCreate(module,&kd,&kernel));CHECK(l.pfnAppendLaunchKernel(regular,kernel,&groups,nullptr,0,nullptr));CHECK(l.pfnAppendLaunchKernel(immediate,kernel,&groups,nullptr,0,nullptr));CHECK(k.pfnDestroy(kernel));CHECK(m.pfnDestroy(module));}
 auto queue=(ze_command_queue_handle_t)(uintptr_t)7;CHECK(q.pfnExecuteCommandLists(queue,1,&regular,nullptr));if(e.pfnCreateCloneExp){ze_command_list_handle_t copied{};CHECK(e.pfnCreateCloneExp(regular,&copied));CHECK(e.pfnImmediateAppendCommandListsExp(immediate,1,&copied,nullptr,0,nullptr));CHECK(l.pfnDestroy(copied));}CHECK(l.pfnDestroy(regular));CHECK(l.pfnDestroy(immediate));std::puts("CPU_SYNTHETIC_ABI_PASS actual_GPU_touch=0");return 0;}
