// Diagnostic interposer for unchanged Half37 ELF; actual extracted LevelZero ABI.
#include <level_zero/ze_api.h>
#include <level_zero/ze_ddi.h>
#include <atomic>
#include <array>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <dlfcn.h>
#include <fcntl.h>
#include <mutex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>
#include <unistd.h>
#include <sys/stat.h>
namespace {
constexpr size_t MAX_BYTES=16u<<20,MAX_TOTAL=64u<<20,MAX_EVENTS=8192,MAX_OBJECTS=512;
std::atomic<bool>capture_failed{false};
bool enabled(){static bool value=std::getenv("HALF37_NATIVE_BINARY_DIR")!=nullptr;return value;}
std::string address(const void*p){char b[64];std::snprintf(b,sizeof(b),"%p",p);return std::string(b);}
std::string hex(const uint8_t*p,size_t n){std::string out;for(size_t i=0;i<n;++i){char b[3];std::snprintf(b,3,"%02x",p[i]);out+=b;}return out;}
std::string quoted(const char* text){std::string out="\"";if(text)for(size_t i=0;text[i]&&i<4096;++i){unsigned char c=text[i];if(c=='"'||c=='\\'){out+='\\';out+=c;}else if(c<32||c>126){char b[7];std::snprintf(b,7,"\\u%04x",c);out+=b;}else out+=c;}return out+'"';}
struct Module{uint64_t id=0;std::string input,native;};struct Kernel{uint64_t id=0,module=0;std::string name;};struct List{uint64_t id=0;bool immediate=false;std::vector<Kernel>kernels;};
struct State{std::mutex lock;int dir=-1;FILE*log=nullptr;size_t events=0,bytes=0;uint64_t sequence=0,id=0;bool failed=false,closed=false;pid_t owner=getpid();std::unordered_map<void*,Module>modules;std::unordered_map<void*,Kernel>kernels;std::unordered_map<void*,List>lists;
 State(){const char*p=std::getenv("HALF37_NATIVE_BINARY_DIR");char actual[4096];if(!p||p[0]!='/'||!realpath(p,actual)||std::strcmp(p,actual)){failed=true;return;}dir=open(p,O_DIRECTORY|O_RDONLY|O_NOFOLLOW|O_CLOEXEC);if(dir<0){failed=true;return;}int fd=openat(dir,"events.jsonl",O_CREAT|O_EXCL|O_WRONLY|O_NOFOLLOW|O_CLOEXEC,0600);if(fd>=0)log=fdopen(fd,"w");if(!log){if(fd>=0)close(fd);failed=true;}}
 void event(const std::string&body){if(closed)return;if(owner!=getpid()){capture_failed.store(true);return;}if(!log||events++>=MAX_EVENTS){failed=true;return;}std::fprintf(log,"{\"sequence\":%llu,\"pid\":%d,%s}\n",(unsigned long long)++sequence,(int)getpid(),body.c_str());if(std::fflush(log)||std::ferror(log))failed=true;}
 void error(const char*message){failed=true;event("\"event\":\"error\",\"message\":"+quoted(message));}
 std::string dump(uint64_t object,const char*role,const void*data,size_t size){if(!data||!size||size>MAX_BYTES||size>MAX_TOTAL-bytes){error("binary bound exceeded");return {};}std::string name="module-"+std::to_string(object)+"-"+role+".bin";int fd=openat(dir,name.c_str(),O_CREAT|O_EXCL|O_WRONLY|O_NOFOLLOW|O_CLOEXEC,0600);if(fd<0){error("exclusive binary output failed");return {};}size_t written=0;while(written<size){ssize_t n=write(fd,(const char*)data+written,size-written);if(n<=0)break;written+=(size_t)n;}int rc=close(fd);if(written!=size||rc){error("complete binary write/close failed");return {};}bytes+=size;return name;}
 void finish(){if(closed)return;closed=true;if(log){std::fprintf(log,"{\"sequence\":%llu,\"pid\":%d,\"event\":\"terminal\",\"failed\":%s,\"events\":%zu,\"binary_bytes\":%zu}\n",(unsigned long long)++sequence,(int)getpid(),(failed||capture_failed.load())?"true":"false",events,bytes);int flushed=std::fflush(log),bad=std::ferror(log),closed_rc=std::fclose(log);if(flushed||bad||closed_rc){capture_failed.store(true);std::fputs("HALF37_INTERPOSER terminal failure\n",stderr);}log=nullptr;}if(dir>=0){close(dir);dir=-1;}}
};State&state(){static State*value=new State;return *value;}
__attribute__((destructor))void finish_capture() noexcept {if(enabled())try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.finish();}catch(...){capture_failed.store(true);std::fputs("HALF37_INTERPOSER terminal failure\n",stderr);}}
using Lookup=void*(*)(void*,const char*);
std::atomic<void*>loaderHandle{nullptr};
Lookup real_lookup() noexcept {static Lookup fn=reinterpret_cast<Lookup>(dlvsym(RTLD_NEXT,"dlsym","GLIBC_2.2.5"));return fn;}
void*lookup(void*handle,const char*name) noexcept {auto f=real_lookup();return f?f(handle,name):nullptr;}
struct DispatchContext{const char*name=nullptr;void*real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
thread_local DispatchContext dispatch;
struct DispatchScope{DispatchContext previous;DispatchScope(const char*n,void*f,void*l,ze_pfnModuleGetNativeBinary_t b):previous(dispatch){dispatch={n,f,l,b};}~DispatchScope(){dispatch=previous;}};
template<class F> F original(const char*name,std::atomic<F>&slot){if(dispatch.name&&std::strcmp(dispatch.name,name)==0)return reinterpret_cast<F>(dispatch.real);if(dispatch.native&&std::strcmp(name,"zeModuleGetNativeBinary")==0)return reinterpret_cast<F>(dispatch.native);F value=slot.load();if(!value){value=reinterpret_cast<F>(lookup(RTLD_NEXT,name));slot.store(value);}return value;}
template<class F> void capture(std::atomic<F>&slot,F value,F wrapper){if(value&&value!=wrapper)slot.store(value);}
#define PTR(NAME,TYPE) std::atomic<TYPE> NAME{nullptr}
PTR(moduleTable,ze_pfnGetModuleProcAddrTable_t);PTR(kernelTable,ze_pfnGetKernelProcAddrTable_t);PTR(listTable,ze_pfnGetCommandListProcAddrTable_t);PTR(queueTable,ze_pfnGetCommandQueueProcAddrTable_t);PTR(expTable,ze_pfnGetCommandListExpProcAddrTable_t);PTR(moduleCreate,ze_pfnModuleCreate_t);PTR(moduleDestroy,ze_pfnModuleDestroy_t);PTR(nativeBinary,ze_pfnModuleGetNativeBinary_t);PTR(kernelCreate,ze_pfnKernelCreate_t);PTR(kernelDestroy,ze_pfnKernelDestroy_t);PTR(listCreate,ze_pfnCommandListCreate_t);PTR(listImmediate,ze_pfnCommandListCreateImmediate_t);PTR(listDestroy,ze_pfnCommandListDestroy_t);PTR(listReset,ze_pfnCommandListReset_t);PTR(launchParams,ze_pfnCommandListAppendLaunchKernelWithParameters_t);PTR(launchArgs,ze_pfnCommandListAppendLaunchKernelWithArguments_t);PTR(launch,ze_pfnCommandListAppendLaunchKernel_t);PTR(execute,ze_pfnCommandQueueExecuteCommandLists_t);PTR(cloneFn,ze_pfnCommandListCreateCloneExp_t);PTR(appendLists,ze_pfnCommandListImmediateAppendCommandListsExp_t);
void submitted(State&s,ze_command_list_handle_t h,const char*via){auto it=s.lists.find(h);if(it==s.lists.end()){s.error("unobserved submitted command list");return;}for(const auto&k:it->second.kernels)s.event("\"event\":\"submitted\",\"via\":"+quoted(via)+",\"list\":"+std::to_string(it->second.id)+",\"kernel\":"+std::to_string(k.id)+",\"module\":"+std::to_string(k.module)+",\"name\":"+quoted(k.name.c_str()));}
}
extern "C" ze_result_t ZE_APICALL zeModuleCreate(ze_context_handle_t c,ze_device_handle_t d,const ze_module_desc_t*desc,ze_module_handle_t*out,ze_module_build_log_handle_t*log){auto f=original("zeModuleCreate",moduleCreate);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(c,d,desc,out,log);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(s.modules.size()>=MAX_OBJECTS){s.error("module bound exceeded");return rc;}Module m;m.id=++s.id;if(desc){m.input=s.dump(m.id,"input",desc->pInputModule,desc->inputSize);}auto native=original("zeModuleGetNativeBinary",nativeBinary);size_t bytes=0;ze_result_t a=native?native(*out,&bytes,nullptr):ZE_RESULT_ERROR_UNINITIALIZED,b=a;if(a==ZE_RESULT_SUCCESS&&bytes&&bytes<=MAX_BYTES){std::vector<uint8_t>raw(bytes);b=native(*out,&bytes,raw.data());if(b==ZE_RESULT_SUCCESS&&bytes<=raw.size())m.native=s.dump(m.id,"native",raw.data(),bytes);}if(m.native.empty())s.error("actual native binary query missing");using Props=ze_result_t(ZE_APICALL*)(ze_device_handle_t,ze_device_properties_t*);auto props=reinterpret_cast<Props>(lookup(dispatch.loader?dispatch.loader:RTLD_NEXT,"zeDeviceGetProperties"));ze_device_properties_t properties{};properties.stype=ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES;auto prc=props?props(d,&properties):ZE_RESULT_ERROR_UNINITIALIZED;s.modules[*out]=m;s.event("\"event\":\"module\",\"context\":"+quoted(address(c).c_str())+",\"device\":"+quoted(address(d).c_str())+",\"device_properties_rc\":"+std::to_string((uint32_t)prc)+",\"device_id\":"+std::to_string(properties.deviceId)+",\"vendor_id\":"+std::to_string(properties.vendorId)+",\"device_uuid\":"+quoted(hex(properties.uuid.id,ZE_MAX_DEVICE_UUID_SIZE).c_str())+",\"device_name\":"+quoted(properties.name)+",\"id\":"+std::to_string(m.id)+",\"format\":"+std::to_string(desc?(int)desc->format:-1)+",\"pnext_present\":"+(desc&&desc->pNext?"true":"false")+",\"constants_present\":"+(desc&&desc->pConstants?"true":"false")+",\"input\":"+quoted(m.input.c_str())+",\"native\":"+quoted(m.native.c_str())+",\"build_flags\":"+quoted(desc?desc->pBuildFlags:nullptr));}catch(...){capture_failed.store(true);std::fputs("HALF37_INTERPOSER capture exception\n",stderr);}return rc;}
extern "C" ze_result_t ZE_APICALL zeModuleDestroy(ze_module_handle_t h){auto f=original("zeModuleDestroy",moduleDestroy);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.modules.erase(h);}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeKernelCreate(ze_module_handle_t m,const ze_kernel_desc_t*d,ze_kernel_handle_t*out){auto f=original("zeKernelCreate",kernelCreate);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(m,d,out);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(s.kernels.size()>=MAX_OBJECTS){s.error("kernel bound exceeded");return rc;}auto it=s.modules.find(m);if(it==s.modules.end()){s.error("kernel module creation unobserved");return rc;}Kernel k{++s.id,it->second.id,d&&d->pKernelName?d->pKernelName:""};s.kernels[*out]=k;s.event("\"event\":\"kernel\",\"id\":"+std::to_string(k.id)+",\"module\":"+std::to_string(k.module)+",\"name\":"+quoted(k.name.c_str()));}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeKernelDestroy(ze_kernel_handle_t h){auto f=original("zeKernelDestroy",kernelDestroy);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.kernels.erase(h);}catch(...){capture_failed.store(true);}return rc;}
#define LIST_CREATE(NAME,SLOT,DESC,IMMEDIATE) extern "C" ze_result_t ZE_APICALL NAME(ze_context_handle_t c,ze_device_handle_t d,const DESC*x,ze_command_list_handle_t*out){auto f=original(#NAME,SLOT);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(c,d,x,out);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(s.lists.size()>=MAX_OBJECTS){s.error("list bound exceeded");return rc;}s.lists[*out]=List{++s.id,IMMEDIATE,{}};}catch(...){capture_failed.store(true);}return rc;}
LIST_CREATE(zeCommandListCreate,listCreate,ze_command_list_desc_t,false)
LIST_CREATE(zeCommandListCreateImmediate,listImmediate,ze_command_queue_desc_t,true)
extern "C" ze_result_t ZE_APICALL zeCommandListDestroy(ze_command_list_handle_t h){auto f=original("zeCommandListDestroy",listDestroy);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.lists.erase(h);}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListReset(ze_command_list_handle_t h){auto f=original("zeCommandListReset",listReset);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto it=s.lists.find(h);if(it!=s.lists.end())it->second.kernels.clear();}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListAppendLaunchKernel(ze_command_list_handle_t h,ze_kernel_handle_t k,const ze_group_count_t*x,ze_event_handle_t signal,uint32_t n,ze_event_handle_t*wait){auto f=original("zeCommandListAppendLaunchKernel",launch);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,k,x,signal,n,wait);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto a=s.lists.find(h);auto b=s.kernels.find(k);if(a==s.lists.end()||b==s.kernels.end())s.error("launch owner unobserved");else if(a->second.kernels.size()>=MAX_OBJECTS)s.error("list kernel bound exceeded");else{a->second.kernels.push_back(b->second);s.event("\"event\":\"append\",\"kernel\":"+std::to_string(b->second.id)+",\"list\":"+std::to_string(a->second.id));if(a->second.immediate){submitted(s,h,"immediate");a->second.kernels.clear();}}}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListAppendLaunchKernelWithParameters(ze_command_list_handle_t h,ze_kernel_handle_t k,const ze_group_count_t*x,const void*params,ze_event_handle_t signal,uint32_t n,ze_event_handle_t*wait){auto f=original("zeCommandListAppendLaunchKernelWithParameters",launchParams);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,k,x,params,signal,n,wait);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto a=s.lists.find(h);auto b=s.kernels.find(k);if(a==s.lists.end()||b==s.kernels.end())s.error("launch owner unobserved");else if(a->second.kernels.size()>=MAX_OBJECTS)s.error("list kernel bound exceeded");else{a->second.kernels.push_back(b->second);s.event("\"event\":\"append\",\"kernel\":"+std::to_string(b->second.id)+",\"list\":"+std::to_string(a->second.id));if(a->second.immediate){submitted(s,h,"immediate");a->second.kernels.clear();}}}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListAppendLaunchKernelWithArguments(ze_command_list_handle_t h,ze_kernel_handle_t k,const ze_group_count_t x,const ze_group_size_t group,void**arguments,const void*params,ze_event_handle_t signal,uint32_t n,ze_event_handle_t*wait){auto f=original("zeCommandListAppendLaunchKernelWithArguments",launchArgs);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,k,x,group,arguments,params,signal,n,wait);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto a=s.lists.find(h);auto b=s.kernels.find(k);if(a==s.lists.end()||b==s.kernels.end())s.error("launch owner unobserved");else if(a->second.kernels.size()>=MAX_OBJECTS)s.error("list kernel bound exceeded");else{a->second.kernels.push_back(b->second);s.event("\"event\":\"append\",\"kernel\":"+std::to_string(b->second.id)+",\"list\":"+std::to_string(a->second.id));if(a->second.immediate){submitted(s,h,"immediate");a->second.kernels.clear();}}}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandQueueExecuteCommandLists(ze_command_queue_handle_t q,uint32_t n,ze_command_list_handle_t*lists,ze_fence_handle_t fence){auto f=original("zeCommandQueueExecuteCommandLists",execute);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(q,n,lists,fence);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(n>MAX_OBJECTS)s.error("submitted list count exceeds bound");else for(uint32_t i=0;i<n;++i)submitted(s,lists[i],"queue");}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListCreateCloneExp(ze_command_list_handle_t h,ze_command_list_handle_t*out){auto f=original("zeCommandListCreateCloneExp",cloneFn);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,out);if(enabled()&&rc==ZE_RESULT_SUCCESS&&out&&*out)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);auto it=s.lists.find(h);if(it==s.lists.end()||s.lists.size()>=MAX_OBJECTS)s.error("clone source owner missing/bounded");else{List copy=it->second;copy.id=++s.id;s.lists[*out]=copy;}}catch(...){capture_failed.store(true);}return rc;}
extern "C" ze_result_t ZE_APICALL zeCommandListImmediateAppendCommandListsExp(ze_command_list_handle_t h,uint32_t n,ze_command_list_handle_t*lists,ze_event_handle_t signal,uint32_t waits,ze_event_handle_t*events){auto f=original("zeCommandListImmediateAppendCommandListsExp",appendLists);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(h,n,lists,signal,waits,events);if(enabled()&&rc==ZE_RESULT_SUCCESS)try{auto&s=state();std::lock_guard<std::mutex>g(s.lock);if(n>MAX_OBJECTS)s.error("graph list count exceeds bound");else for(uint32_t i=0;i<n;++i)submitted(s,lists[i],"immediate-graph");}catch(...){capture_failed.store(true);}return rc;}
namespace {
ze_pfnModuleCreate_t bind_zeModuleCreate(ze_pfnModuleCreate_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnModuleDestroy_t bind_zeModuleDestroy(ze_pfnModuleDestroy_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnKernelCreate_t bind_zeKernelCreate(ze_pfnKernelCreate_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnKernelDestroy_t bind_zeKernelDestroy(ze_pfnKernelDestroy_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListCreate_t bind_zeCommandListCreate(ze_pfnCommandListCreate_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListCreateImmediate_t bind_zeCommandListCreateImmediate(ze_pfnCommandListCreateImmediate_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListDestroy_t bind_zeCommandListDestroy(ze_pfnCommandListDestroy_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListReset_t bind_zeCommandListReset(ze_pfnCommandListReset_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListAppendLaunchKernel_t bind_zeCommandListAppendLaunchKernel(ze_pfnCommandListAppendLaunchKernel_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListAppendLaunchKernelWithParameters_t bind_zeCommandListAppendLaunchKernelWithParameters(ze_pfnCommandListAppendLaunchKernelWithParameters_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListAppendLaunchKernelWithArguments_t bind_zeCommandListAppendLaunchKernelWithArguments(ze_pfnCommandListAppendLaunchKernelWithArguments_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandQueueExecuteCommandLists_t bind_zeCommandQueueExecuteCommandLists(ze_pfnCommandQueueExecuteCommandLists_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListCreateCloneExp_t bind_zeCommandListCreateCloneExp(ze_pfnCommandListCreateCloneExp_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnCommandListImmediateAppendCommandListsExp_t bind_zeCommandListImmediateAppendCommandListsExp(ze_pfnCommandListImmediateAppendCommandListsExp_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnGetModuleProcAddrTable_t bind_zeGetModuleProcAddrTable(ze_pfnGetModuleProcAddrTable_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnGetKernelProcAddrTable_t bind_zeGetKernelProcAddrTable(ze_pfnGetKernelProcAddrTable_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnGetCommandListProcAddrTable_t bind_zeGetCommandListProcAddrTable(ze_pfnGetCommandListProcAddrTable_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnGetCommandQueueProcAddrTable_t bind_zeGetCommandQueueProcAddrTable(ze_pfnGetCommandQueueProcAddrTable_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
ze_pfnGetCommandListExpProcAddrTable_t bind_zeGetCommandListExpProcAddrTable(ze_pfnGetCommandListExpProcAddrTable_t,void*,ze_pfnModuleGetNativeBinary_t=nullptr);
}
#define TABLE(NAME,TYPE,SLOT,BODY) extern "C" ze_result_t ZE_APICALL NAME(ze_api_version_t version,TYPE*table){using F=ze_result_t(ZE_APICALL*)(ze_api_version_t,TYPE*);auto f=original(#NAME,SLOT);if(!f)return ZE_RESULT_ERROR_UNINITIALIZED;auto rc=f(version,table);if(enabled()&&rc==ZE_RESULT_SUCCESS&&table)try{BODY;auto&s=state();std::lock_guard<std::mutex>g(s.lock);s.event("\"event\":\"proc_table\",\"name\":"+quoted(#NAME)+",\"version\":"+std::to_string((uint32_t)version));}catch(...){capture_failed.store(true);}return rc;}
#define HOOK(FIELD,SLOT,WRAPPER) if(table->FIELD)table->FIELD=bind_##WRAPPER(table->FIELD,dispatch.loader)
TABLE(zeGetModuleProcAddrTable,ze_module_dditable_t,moduleTable,if(table->pfnCreate)table->pfnCreate=bind_zeModuleCreate(table->pfnCreate,dispatch.loader,table->pfnGetNativeBinary);HOOK(pfnDestroy,moduleDestroy,zeModuleDestroy))
TABLE(zeGetKernelProcAddrTable,ze_kernel_dditable_t,kernelTable,HOOK(pfnCreate,kernelCreate,zeKernelCreate);HOOK(pfnDestroy,kernelDestroy,zeKernelDestroy))
TABLE(zeGetCommandListProcAddrTable,ze_command_list_dditable_t,listTable,HOOK(pfnCreate,listCreate,zeCommandListCreate);HOOK(pfnCreateImmediate,listImmediate,zeCommandListCreateImmediate);HOOK(pfnDestroy,listDestroy,zeCommandListDestroy);HOOK(pfnReset,listReset,zeCommandListReset);HOOK(pfnAppendLaunchKernel,launch,zeCommandListAppendLaunchKernel);HOOK(pfnAppendLaunchKernelWithParameters,launchParams,zeCommandListAppendLaunchKernelWithParameters);HOOK(pfnAppendLaunchKernelWithArguments,launchArgs,zeCommandListAppendLaunchKernelWithArguments))
TABLE(zeGetCommandQueueProcAddrTable,ze_command_queue_dditable_t,queueTable,HOOK(pfnExecuteCommandLists,execute,zeCommandQueueExecuteCommandLists))
TABLE(zeGetCommandListExpProcAddrTable,ze_command_list_exp_dditable_t,expTable,HOOK(pfnCreateCloneExp,cloneFn,zeCommandListCreateCloneExp);HOOK(pfnImmediateAppendCommandListsExp,appendLists,zeCommandListImmediateAppendCommandListsExp))

namespace {
std::mutex&endpointMutex(){static std::mutex*value=new std::mutex;return *value;}
struct zeModuleCreate_Endpoint{ze_pfnModuleCreate_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeModuleCreate_Endpoint*>,8>zeModuleCreate_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeModuleCreate_Thunk(ze_context_handle_t c,ze_device_handle_t d,const ze_module_desc_t*desc,ze_module_handle_t*out,ze_module_build_log_handle_t*log){const auto e=*zeModuleCreate_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeModuleCreate",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeModuleCreate(c,d,desc,out,log);}
ze_pfnModuleCreate_t bind_zeModuleCreate(ze_pfnModuleCreate_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeModuleCreate)real=reinterpret_cast<ze_pfnModuleCreate_t>(lookup(RTLD_NEXT,"zeModuleCreate"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnModuleCreate_t thunks[]={&zeModuleCreate_Thunk<0>,&zeModuleCreate_Thunk<1>,&zeModuleCreate_Thunk<2>,&zeModuleCreate_Thunk<3>,&zeModuleCreate_Thunk<4>,&zeModuleCreate_Thunk<5>,&zeModuleCreate_Thunk<6>,&zeModuleCreate_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeModuleCreate_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeModuleCreate_Endpoint{real,loader,native};zeModuleCreate_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeModuleDestroy_Endpoint{ze_pfnModuleDestroy_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeModuleDestroy_Endpoint*>,8>zeModuleDestroy_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeModuleDestroy_Thunk(ze_module_handle_t h){const auto e=*zeModuleDestroy_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeModuleDestroy",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeModuleDestroy(h);}
ze_pfnModuleDestroy_t bind_zeModuleDestroy(ze_pfnModuleDestroy_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeModuleDestroy)real=reinterpret_cast<ze_pfnModuleDestroy_t>(lookup(RTLD_NEXT,"zeModuleDestroy"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnModuleDestroy_t thunks[]={&zeModuleDestroy_Thunk<0>,&zeModuleDestroy_Thunk<1>,&zeModuleDestroy_Thunk<2>,&zeModuleDestroy_Thunk<3>,&zeModuleDestroy_Thunk<4>,&zeModuleDestroy_Thunk<5>,&zeModuleDestroy_Thunk<6>,&zeModuleDestroy_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeModuleDestroy_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeModuleDestroy_Endpoint{real,loader,native};zeModuleDestroy_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeKernelCreate_Endpoint{ze_pfnKernelCreate_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeKernelCreate_Endpoint*>,8>zeKernelCreate_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeKernelCreate_Thunk(ze_module_handle_t m,const ze_kernel_desc_t*d,ze_kernel_handle_t*out){const auto e=*zeKernelCreate_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeKernelCreate",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeKernelCreate(m,d,out);}
ze_pfnKernelCreate_t bind_zeKernelCreate(ze_pfnKernelCreate_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeKernelCreate)real=reinterpret_cast<ze_pfnKernelCreate_t>(lookup(RTLD_NEXT,"zeKernelCreate"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnKernelCreate_t thunks[]={&zeKernelCreate_Thunk<0>,&zeKernelCreate_Thunk<1>,&zeKernelCreate_Thunk<2>,&zeKernelCreate_Thunk<3>,&zeKernelCreate_Thunk<4>,&zeKernelCreate_Thunk<5>,&zeKernelCreate_Thunk<6>,&zeKernelCreate_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeKernelCreate_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeKernelCreate_Endpoint{real,loader,native};zeKernelCreate_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeKernelDestroy_Endpoint{ze_pfnKernelDestroy_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeKernelDestroy_Endpoint*>,8>zeKernelDestroy_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeKernelDestroy_Thunk(ze_kernel_handle_t h){const auto e=*zeKernelDestroy_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeKernelDestroy",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeKernelDestroy(h);}
ze_pfnKernelDestroy_t bind_zeKernelDestroy(ze_pfnKernelDestroy_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeKernelDestroy)real=reinterpret_cast<ze_pfnKernelDestroy_t>(lookup(RTLD_NEXT,"zeKernelDestroy"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnKernelDestroy_t thunks[]={&zeKernelDestroy_Thunk<0>,&zeKernelDestroy_Thunk<1>,&zeKernelDestroy_Thunk<2>,&zeKernelDestroy_Thunk<3>,&zeKernelDestroy_Thunk<4>,&zeKernelDestroy_Thunk<5>,&zeKernelDestroy_Thunk<6>,&zeKernelDestroy_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeKernelDestroy_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeKernelDestroy_Endpoint{real,loader,native};zeKernelDestroy_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListCreate_Endpoint{ze_pfnCommandListCreate_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListCreate_Endpoint*>,8>zeCommandListCreate_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListCreate_Thunk(ze_context_handle_t c,ze_device_handle_t d,const ze_command_list_desc_t*x,ze_command_list_handle_t*out){const auto e=*zeCommandListCreate_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListCreate",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListCreate(c,d,x,out);}
ze_pfnCommandListCreate_t bind_zeCommandListCreate(ze_pfnCommandListCreate_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListCreate)real=reinterpret_cast<ze_pfnCommandListCreate_t>(lookup(RTLD_NEXT,"zeCommandListCreate"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListCreate_t thunks[]={&zeCommandListCreate_Thunk<0>,&zeCommandListCreate_Thunk<1>,&zeCommandListCreate_Thunk<2>,&zeCommandListCreate_Thunk<3>,&zeCommandListCreate_Thunk<4>,&zeCommandListCreate_Thunk<5>,&zeCommandListCreate_Thunk<6>,&zeCommandListCreate_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListCreate_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListCreate_Endpoint{real,loader,native};zeCommandListCreate_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListCreateImmediate_Endpoint{ze_pfnCommandListCreateImmediate_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListCreateImmediate_Endpoint*>,8>zeCommandListCreateImmediate_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListCreateImmediate_Thunk(ze_context_handle_t c,ze_device_handle_t d,const ze_command_queue_desc_t*x,ze_command_list_handle_t*out){const auto e=*zeCommandListCreateImmediate_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListCreateImmediate",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListCreateImmediate(c,d,x,out);}
ze_pfnCommandListCreateImmediate_t bind_zeCommandListCreateImmediate(ze_pfnCommandListCreateImmediate_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListCreateImmediate)real=reinterpret_cast<ze_pfnCommandListCreateImmediate_t>(lookup(RTLD_NEXT,"zeCommandListCreateImmediate"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListCreateImmediate_t thunks[]={&zeCommandListCreateImmediate_Thunk<0>,&zeCommandListCreateImmediate_Thunk<1>,&zeCommandListCreateImmediate_Thunk<2>,&zeCommandListCreateImmediate_Thunk<3>,&zeCommandListCreateImmediate_Thunk<4>,&zeCommandListCreateImmediate_Thunk<5>,&zeCommandListCreateImmediate_Thunk<6>,&zeCommandListCreateImmediate_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListCreateImmediate_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListCreateImmediate_Endpoint{real,loader,native};zeCommandListCreateImmediate_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListDestroy_Endpoint{ze_pfnCommandListDestroy_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListDestroy_Endpoint*>,8>zeCommandListDestroy_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListDestroy_Thunk(ze_command_list_handle_t h){const auto e=*zeCommandListDestroy_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListDestroy",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListDestroy(h);}
ze_pfnCommandListDestroy_t bind_zeCommandListDestroy(ze_pfnCommandListDestroy_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListDestroy)real=reinterpret_cast<ze_pfnCommandListDestroy_t>(lookup(RTLD_NEXT,"zeCommandListDestroy"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListDestroy_t thunks[]={&zeCommandListDestroy_Thunk<0>,&zeCommandListDestroy_Thunk<1>,&zeCommandListDestroy_Thunk<2>,&zeCommandListDestroy_Thunk<3>,&zeCommandListDestroy_Thunk<4>,&zeCommandListDestroy_Thunk<5>,&zeCommandListDestroy_Thunk<6>,&zeCommandListDestroy_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListDestroy_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListDestroy_Endpoint{real,loader,native};zeCommandListDestroy_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListReset_Endpoint{ze_pfnCommandListReset_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListReset_Endpoint*>,8>zeCommandListReset_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListReset_Thunk(ze_command_list_handle_t h){const auto e=*zeCommandListReset_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListReset",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListReset(h);}
ze_pfnCommandListReset_t bind_zeCommandListReset(ze_pfnCommandListReset_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListReset)real=reinterpret_cast<ze_pfnCommandListReset_t>(lookup(RTLD_NEXT,"zeCommandListReset"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListReset_t thunks[]={&zeCommandListReset_Thunk<0>,&zeCommandListReset_Thunk<1>,&zeCommandListReset_Thunk<2>,&zeCommandListReset_Thunk<3>,&zeCommandListReset_Thunk<4>,&zeCommandListReset_Thunk<5>,&zeCommandListReset_Thunk<6>,&zeCommandListReset_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListReset_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListReset_Endpoint{real,loader,native};zeCommandListReset_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListAppendLaunchKernel_Endpoint{ze_pfnCommandListAppendLaunchKernel_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListAppendLaunchKernel_Endpoint*>,8>zeCommandListAppendLaunchKernel_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListAppendLaunchKernel_Thunk(ze_command_list_handle_t h,ze_kernel_handle_t k,const ze_group_count_t*x,ze_event_handle_t event,uint32_t n,ze_event_handle_t*wait){const auto e=*zeCommandListAppendLaunchKernel_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListAppendLaunchKernel",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListAppendLaunchKernel(h,k,x,event,n,wait);}
ze_pfnCommandListAppendLaunchKernel_t bind_zeCommandListAppendLaunchKernel(ze_pfnCommandListAppendLaunchKernel_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListAppendLaunchKernel)real=reinterpret_cast<ze_pfnCommandListAppendLaunchKernel_t>(lookup(RTLD_NEXT,"zeCommandListAppendLaunchKernel"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListAppendLaunchKernel_t thunks[]={&zeCommandListAppendLaunchKernel_Thunk<0>,&zeCommandListAppendLaunchKernel_Thunk<1>,&zeCommandListAppendLaunchKernel_Thunk<2>,&zeCommandListAppendLaunchKernel_Thunk<3>,&zeCommandListAppendLaunchKernel_Thunk<4>,&zeCommandListAppendLaunchKernel_Thunk<5>,&zeCommandListAppendLaunchKernel_Thunk<6>,&zeCommandListAppendLaunchKernel_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListAppendLaunchKernel_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListAppendLaunchKernel_Endpoint{real,loader,native};zeCommandListAppendLaunchKernel_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListAppendLaunchKernelWithParameters_Endpoint{ze_pfnCommandListAppendLaunchKernelWithParameters_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListAppendLaunchKernelWithParameters_Endpoint*>,8>zeCommandListAppendLaunchKernelWithParameters_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListAppendLaunchKernelWithParameters_Thunk(ze_command_list_handle_t h,ze_kernel_handle_t k,const ze_group_count_t*x,const void*params,ze_event_handle_t event,uint32_t n,ze_event_handle_t*wait){const auto e=*zeCommandListAppendLaunchKernelWithParameters_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListAppendLaunchKernelWithParameters",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListAppendLaunchKernelWithParameters(h,k,x,params,event,n,wait);}
ze_pfnCommandListAppendLaunchKernelWithParameters_t bind_zeCommandListAppendLaunchKernelWithParameters(ze_pfnCommandListAppendLaunchKernelWithParameters_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListAppendLaunchKernelWithParameters)real=reinterpret_cast<ze_pfnCommandListAppendLaunchKernelWithParameters_t>(lookup(RTLD_NEXT,"zeCommandListAppendLaunchKernelWithParameters"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListAppendLaunchKernelWithParameters_t thunks[]={&zeCommandListAppendLaunchKernelWithParameters_Thunk<0>,&zeCommandListAppendLaunchKernelWithParameters_Thunk<1>,&zeCommandListAppendLaunchKernelWithParameters_Thunk<2>,&zeCommandListAppendLaunchKernelWithParameters_Thunk<3>,&zeCommandListAppendLaunchKernelWithParameters_Thunk<4>,&zeCommandListAppendLaunchKernelWithParameters_Thunk<5>,&zeCommandListAppendLaunchKernelWithParameters_Thunk<6>,&zeCommandListAppendLaunchKernelWithParameters_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListAppendLaunchKernelWithParameters_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListAppendLaunchKernelWithParameters_Endpoint{real,loader,native};zeCommandListAppendLaunchKernelWithParameters_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListAppendLaunchKernelWithArguments_Endpoint{ze_pfnCommandListAppendLaunchKernelWithArguments_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListAppendLaunchKernelWithArguments_Endpoint*>,8>zeCommandListAppendLaunchKernelWithArguments_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListAppendLaunchKernelWithArguments_Thunk(ze_command_list_handle_t h,ze_kernel_handle_t k,const ze_group_count_t x,const ze_group_size_t group,void**args,const void*params,ze_event_handle_t event,uint32_t n,ze_event_handle_t*wait){const auto e=*zeCommandListAppendLaunchKernelWithArguments_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListAppendLaunchKernelWithArguments",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListAppendLaunchKernelWithArguments(h,k,x,group,args,params,event,n,wait);}
ze_pfnCommandListAppendLaunchKernelWithArguments_t bind_zeCommandListAppendLaunchKernelWithArguments(ze_pfnCommandListAppendLaunchKernelWithArguments_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListAppendLaunchKernelWithArguments)real=reinterpret_cast<ze_pfnCommandListAppendLaunchKernelWithArguments_t>(lookup(RTLD_NEXT,"zeCommandListAppendLaunchKernelWithArguments"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListAppendLaunchKernelWithArguments_t thunks[]={&zeCommandListAppendLaunchKernelWithArguments_Thunk<0>,&zeCommandListAppendLaunchKernelWithArguments_Thunk<1>,&zeCommandListAppendLaunchKernelWithArguments_Thunk<2>,&zeCommandListAppendLaunchKernelWithArguments_Thunk<3>,&zeCommandListAppendLaunchKernelWithArguments_Thunk<4>,&zeCommandListAppendLaunchKernelWithArguments_Thunk<5>,&zeCommandListAppendLaunchKernelWithArguments_Thunk<6>,&zeCommandListAppendLaunchKernelWithArguments_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListAppendLaunchKernelWithArguments_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListAppendLaunchKernelWithArguments_Endpoint{real,loader,native};zeCommandListAppendLaunchKernelWithArguments_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandQueueExecuteCommandLists_Endpoint{ze_pfnCommandQueueExecuteCommandLists_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandQueueExecuteCommandLists_Endpoint*>,8>zeCommandQueueExecuteCommandLists_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandQueueExecuteCommandLists_Thunk(ze_command_queue_handle_t q,uint32_t n,ze_command_list_handle_t*lists,ze_fence_handle_t f){const auto e=*zeCommandQueueExecuteCommandLists_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandQueueExecuteCommandLists",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandQueueExecuteCommandLists(q,n,lists,f);}
ze_pfnCommandQueueExecuteCommandLists_t bind_zeCommandQueueExecuteCommandLists(ze_pfnCommandQueueExecuteCommandLists_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandQueueExecuteCommandLists)real=reinterpret_cast<ze_pfnCommandQueueExecuteCommandLists_t>(lookup(RTLD_NEXT,"zeCommandQueueExecuteCommandLists"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandQueueExecuteCommandLists_t thunks[]={&zeCommandQueueExecuteCommandLists_Thunk<0>,&zeCommandQueueExecuteCommandLists_Thunk<1>,&zeCommandQueueExecuteCommandLists_Thunk<2>,&zeCommandQueueExecuteCommandLists_Thunk<3>,&zeCommandQueueExecuteCommandLists_Thunk<4>,&zeCommandQueueExecuteCommandLists_Thunk<5>,&zeCommandQueueExecuteCommandLists_Thunk<6>,&zeCommandQueueExecuteCommandLists_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandQueueExecuteCommandLists_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandQueueExecuteCommandLists_Endpoint{real,loader,native};zeCommandQueueExecuteCommandLists_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListCreateCloneExp_Endpoint{ze_pfnCommandListCreateCloneExp_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListCreateCloneExp_Endpoint*>,8>zeCommandListCreateCloneExp_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListCreateCloneExp_Thunk(ze_command_list_handle_t h,ze_command_list_handle_t*out){const auto e=*zeCommandListCreateCloneExp_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListCreateCloneExp",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListCreateCloneExp(h,out);}
ze_pfnCommandListCreateCloneExp_t bind_zeCommandListCreateCloneExp(ze_pfnCommandListCreateCloneExp_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListCreateCloneExp)real=reinterpret_cast<ze_pfnCommandListCreateCloneExp_t>(lookup(RTLD_NEXT,"zeCommandListCreateCloneExp"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListCreateCloneExp_t thunks[]={&zeCommandListCreateCloneExp_Thunk<0>,&zeCommandListCreateCloneExp_Thunk<1>,&zeCommandListCreateCloneExp_Thunk<2>,&zeCommandListCreateCloneExp_Thunk<3>,&zeCommandListCreateCloneExp_Thunk<4>,&zeCommandListCreateCloneExp_Thunk<5>,&zeCommandListCreateCloneExp_Thunk<6>,&zeCommandListCreateCloneExp_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListCreateCloneExp_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListCreateCloneExp_Endpoint{real,loader,native};zeCommandListCreateCloneExp_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeCommandListImmediateAppendCommandListsExp_Endpoint{ze_pfnCommandListImmediateAppendCommandListsExp_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeCommandListImmediateAppendCommandListsExp_Endpoint*>,8>zeCommandListImmediateAppendCommandListsExp_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeCommandListImmediateAppendCommandListsExp_Thunk(ze_command_list_handle_t h,uint32_t n,ze_command_list_handle_t*lists,ze_event_handle_t event,uint32_t nw,ze_event_handle_t*wait){const auto e=*zeCommandListImmediateAppendCommandListsExp_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeCommandListImmediateAppendCommandListsExp",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeCommandListImmediateAppendCommandListsExp(h,n,lists,event,nw,wait);}
ze_pfnCommandListImmediateAppendCommandListsExp_t bind_zeCommandListImmediateAppendCommandListsExp(ze_pfnCommandListImmediateAppendCommandListsExp_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeCommandListImmediateAppendCommandListsExp)real=reinterpret_cast<ze_pfnCommandListImmediateAppendCommandListsExp_t>(lookup(RTLD_NEXT,"zeCommandListImmediateAppendCommandListsExp"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnCommandListImmediateAppendCommandListsExp_t thunks[]={&zeCommandListImmediateAppendCommandListsExp_Thunk<0>,&zeCommandListImmediateAppendCommandListsExp_Thunk<1>,&zeCommandListImmediateAppendCommandListsExp_Thunk<2>,&zeCommandListImmediateAppendCommandListsExp_Thunk<3>,&zeCommandListImmediateAppendCommandListsExp_Thunk<4>,&zeCommandListImmediateAppendCommandListsExp_Thunk<5>,&zeCommandListImmediateAppendCommandListsExp_Thunk<6>,&zeCommandListImmediateAppendCommandListsExp_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeCommandListImmediateAppendCommandListsExp_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeCommandListImmediateAppendCommandListsExp_Endpoint{real,loader,native};zeCommandListImmediateAppendCommandListsExp_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeGetModuleProcAddrTable_Endpoint{ze_pfnGetModuleProcAddrTable_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeGetModuleProcAddrTable_Endpoint*>,8>zeGetModuleProcAddrTable_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeGetModuleProcAddrTable_Thunk(ze_api_version_t v,ze_module_dditable_t*t){const auto e=*zeGetModuleProcAddrTable_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeGetModuleProcAddrTable",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeGetModuleProcAddrTable(v,t);}
ze_pfnGetModuleProcAddrTable_t bind_zeGetModuleProcAddrTable(ze_pfnGetModuleProcAddrTable_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeGetModuleProcAddrTable)real=reinterpret_cast<ze_pfnGetModuleProcAddrTable_t>(lookup(RTLD_NEXT,"zeGetModuleProcAddrTable"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnGetModuleProcAddrTable_t thunks[]={&zeGetModuleProcAddrTable_Thunk<0>,&zeGetModuleProcAddrTable_Thunk<1>,&zeGetModuleProcAddrTable_Thunk<2>,&zeGetModuleProcAddrTable_Thunk<3>,&zeGetModuleProcAddrTable_Thunk<4>,&zeGetModuleProcAddrTable_Thunk<5>,&zeGetModuleProcAddrTable_Thunk<6>,&zeGetModuleProcAddrTable_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeGetModuleProcAddrTable_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeGetModuleProcAddrTable_Endpoint{real,loader,native};zeGetModuleProcAddrTable_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeGetKernelProcAddrTable_Endpoint{ze_pfnGetKernelProcAddrTable_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeGetKernelProcAddrTable_Endpoint*>,8>zeGetKernelProcAddrTable_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeGetKernelProcAddrTable_Thunk(ze_api_version_t v,ze_kernel_dditable_t*t){const auto e=*zeGetKernelProcAddrTable_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeGetKernelProcAddrTable",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeGetKernelProcAddrTable(v,t);}
ze_pfnGetKernelProcAddrTable_t bind_zeGetKernelProcAddrTable(ze_pfnGetKernelProcAddrTable_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeGetKernelProcAddrTable)real=reinterpret_cast<ze_pfnGetKernelProcAddrTable_t>(lookup(RTLD_NEXT,"zeGetKernelProcAddrTable"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnGetKernelProcAddrTable_t thunks[]={&zeGetKernelProcAddrTable_Thunk<0>,&zeGetKernelProcAddrTable_Thunk<1>,&zeGetKernelProcAddrTable_Thunk<2>,&zeGetKernelProcAddrTable_Thunk<3>,&zeGetKernelProcAddrTable_Thunk<4>,&zeGetKernelProcAddrTable_Thunk<5>,&zeGetKernelProcAddrTable_Thunk<6>,&zeGetKernelProcAddrTable_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeGetKernelProcAddrTable_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeGetKernelProcAddrTable_Endpoint{real,loader,native};zeGetKernelProcAddrTable_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeGetCommandListProcAddrTable_Endpoint{ze_pfnGetCommandListProcAddrTable_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeGetCommandListProcAddrTable_Endpoint*>,8>zeGetCommandListProcAddrTable_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeGetCommandListProcAddrTable_Thunk(ze_api_version_t v,ze_command_list_dditable_t*t){const auto e=*zeGetCommandListProcAddrTable_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeGetCommandListProcAddrTable",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeGetCommandListProcAddrTable(v,t);}
ze_pfnGetCommandListProcAddrTable_t bind_zeGetCommandListProcAddrTable(ze_pfnGetCommandListProcAddrTable_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeGetCommandListProcAddrTable)real=reinterpret_cast<ze_pfnGetCommandListProcAddrTable_t>(lookup(RTLD_NEXT,"zeGetCommandListProcAddrTable"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnGetCommandListProcAddrTable_t thunks[]={&zeGetCommandListProcAddrTable_Thunk<0>,&zeGetCommandListProcAddrTable_Thunk<1>,&zeGetCommandListProcAddrTable_Thunk<2>,&zeGetCommandListProcAddrTable_Thunk<3>,&zeGetCommandListProcAddrTable_Thunk<4>,&zeGetCommandListProcAddrTable_Thunk<5>,&zeGetCommandListProcAddrTable_Thunk<6>,&zeGetCommandListProcAddrTable_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeGetCommandListProcAddrTable_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeGetCommandListProcAddrTable_Endpoint{real,loader,native};zeGetCommandListProcAddrTable_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeGetCommandQueueProcAddrTable_Endpoint{ze_pfnGetCommandQueueProcAddrTable_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeGetCommandQueueProcAddrTable_Endpoint*>,8>zeGetCommandQueueProcAddrTable_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeGetCommandQueueProcAddrTable_Thunk(ze_api_version_t v,ze_command_queue_dditable_t*t){const auto e=*zeGetCommandQueueProcAddrTable_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeGetCommandQueueProcAddrTable",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeGetCommandQueueProcAddrTable(v,t);}
ze_pfnGetCommandQueueProcAddrTable_t bind_zeGetCommandQueueProcAddrTable(ze_pfnGetCommandQueueProcAddrTable_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeGetCommandQueueProcAddrTable)real=reinterpret_cast<ze_pfnGetCommandQueueProcAddrTable_t>(lookup(RTLD_NEXT,"zeGetCommandQueueProcAddrTable"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnGetCommandQueueProcAddrTable_t thunks[]={&zeGetCommandQueueProcAddrTable_Thunk<0>,&zeGetCommandQueueProcAddrTable_Thunk<1>,&zeGetCommandQueueProcAddrTable_Thunk<2>,&zeGetCommandQueueProcAddrTable_Thunk<3>,&zeGetCommandQueueProcAddrTable_Thunk<4>,&zeGetCommandQueueProcAddrTable_Thunk<5>,&zeGetCommandQueueProcAddrTable_Thunk<6>,&zeGetCommandQueueProcAddrTable_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeGetCommandQueueProcAddrTable_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeGetCommandQueueProcAddrTable_Endpoint{real,loader,native};zeGetCommandQueueProcAddrTable_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
struct zeGetCommandListExpProcAddrTable_Endpoint{ze_pfnGetCommandListExpProcAddrTable_t real=nullptr;void*loader=nullptr;ze_pfnModuleGetNativeBinary_t native=nullptr;};
std::array<std::atomic<zeGetCommandListExpProcAddrTable_Endpoint*>,8>zeGetCommandListExpProcAddrTable_Endpoints{};
template<size_t I>ze_result_t ZE_APICALL zeGetCommandListExpProcAddrTable_Thunk(ze_api_version_t v,ze_command_list_exp_dditable_t*t){const auto e=*zeGetCommandListExpProcAddrTable_Endpoints[I].load(std::memory_order_acquire);DispatchScope scope("zeGetCommandListExpProcAddrTable",reinterpret_cast<void*>(e.real),e.loader,e.native);return zeGetCommandListExpProcAddrTable(v,t);}
ze_pfnGetCommandListExpProcAddrTable_t bind_zeGetCommandListExpProcAddrTable(ze_pfnGetCommandListExpProcAddrTable_t real,void*loader,ze_pfnModuleGetNativeBinary_t native){if(!real)return nullptr;if(real==&zeGetCommandListExpProcAddrTable)real=reinterpret_cast<ze_pfnGetCommandListExpProcAddrTable_t>(lookup(RTLD_NEXT,"zeGetCommandListExpProcAddrTable"));std::lock_guard<std::mutex>g(endpointMutex());static const ze_pfnGetCommandListExpProcAddrTable_t thunks[]={&zeGetCommandListExpProcAddrTable_Thunk<0>,&zeGetCommandListExpProcAddrTable_Thunk<1>,&zeGetCommandListExpProcAddrTable_Thunk<2>,&zeGetCommandListExpProcAddrTable_Thunk<3>,&zeGetCommandListExpProcAddrTable_Thunk<4>,&zeGetCommandListExpProcAddrTable_Thunk<5>,&zeGetCommandListExpProcAddrTable_Thunk<6>,&zeGetCommandListExpProcAddrTable_Thunk<7>};for(size_t i=0;i<8;++i){auto*e=zeGetCommandListExpProcAddrTable_Endpoints[i].load(std::memory_order_relaxed);if(e&&e->real==real&&e->loader==loader&&e->native==native)return thunks[i];if(!e){auto*created=new zeGetCommandListExpProcAddrTable_Endpoint{real,loader,native};zeGetCommandListExpProcAddrTable_Endpoints[i].store(created,std::memory_order_release);return thunks[i];}}capture_failed.store(true);return real;}
}

// GNU libc x86_64 versioned resolver is independently exercised by CPU fixture.
extern "C" void*dlsym(void*handle,const char*name) noexcept {
 void*value=lookup(handle,name);if(!enabled()||!value)return value;
 try {
  Dl_info caller{};dladdr(__builtin_return_address(0),&caller);const char*path=caller.dli_fname?caller.dli_fname:"";const char*base=std::strrchr(path,'/');base=base?base+1:path;bool redirect=std::strncmp(base,"libur_adapter_level_zero",24)==0||std::strcmp(base,"half37_fake_main")==0;
  if(std::strncmp(name,"ze",2)==0){if(redirect)loaderHandle.store(handle);auto&s=state();std::lock_guard<std::mutex>g(s.lock);Dl_info info{};dladdr(value,&info);s.event("\"event\":\"symbol_lookup\",\"name\":"+quoted(name)+",\"library\":"+quoted(info.dli_fname)+",\"caller\":"+quoted(path)+",\"redirected\":"+(redirect?"true":"false"));}
  if(!redirect)return value;
#define SYMBOL(NAME,SLOT) if(std::strcmp(name,#NAME)==0)return reinterpret_cast<void*>(bind_##NAME(reinterpret_cast<decltype(&NAME)>(value),handle));
  if(std::strcmp(name,"zeModuleCreate")==0)return reinterpret_cast<void*>(bind_zeModuleCreate(reinterpret_cast<ze_pfnModuleCreate_t>(value),handle,reinterpret_cast<ze_pfnModuleGetNativeBinary_t>(lookup(handle,"zeModuleGetNativeBinary")))); SYMBOL(zeModuleDestroy,moduleDestroy)
  SYMBOL(zeKernelCreate,kernelCreate) SYMBOL(zeKernelDestroy,kernelDestroy)
  SYMBOL(zeCommandListCreate,listCreate) SYMBOL(zeCommandListCreateImmediate,listImmediate)
  SYMBOL(zeCommandListDestroy,listDestroy) SYMBOL(zeCommandListReset,listReset)
  SYMBOL(zeCommandListAppendLaunchKernelWithParameters,launchParams) SYMBOL(zeCommandListAppendLaunchKernelWithArguments,launchArgs) SYMBOL(zeCommandListAppendLaunchKernel,launch) SYMBOL(zeCommandQueueExecuteCommandLists,execute)
  SYMBOL(zeCommandListCreateCloneExp,cloneFn) SYMBOL(zeCommandListImmediateAppendCommandListsExp,appendLists)
  SYMBOL(zeGetModuleProcAddrTable,moduleTable) SYMBOL(zeGetKernelProcAddrTable,kernelTable)
  SYMBOL(zeGetCommandListProcAddrTable,listTable) SYMBOL(zeGetCommandQueueProcAddrTable,queueTable)
  SYMBOL(zeGetCommandListExpProcAddrTable,expTable)
#undef SYMBOL
 }catch(...){capture_failed.store(true);}
 return value;
}
