"""Saved logical byte/provenance witness plus independent current epoch join."""
import math,base64,hashlib,re
from pathlib import Path
from logical_free_immutable_epoch_v2 import WORKER,PARSER_SHA,WORKER_SHA
from serial37_canonical_json_v3 import canonical
from logical_free_require_case_epoch_v2 import RequireLogicalEpoch

def require(ok,message):
 if not ok:raise ValueError(message)
def binding(proof,epoch,owner_pid,predevice_deadline,postoperation_floor,*,case_specs,ready_boundary=None,ack_epoch=None):
 require(type(epoch)is RequireLogicalEpoch,'Independent current logical epoch required');RequireLogicalEpoch.implementation_binding(epoch);epoch.evidence._owned();require(proof['passed']is True and type(proof['owner_pid'])is int and proof['owner_pid']==owner_pid and not proof['worker_errors'] and proof['live_guards_reused']is False and proof['saved_result_imported']is False,'Actual saved logical owner/failure/scope differs');require(canonical(proof['worker_runtime'])==canonical(epoch.runtime),'Actual saved/current worker runtime closure differs');w=proof['evidence_byte_witness'];require(w['owner_pid']==owner_pid and w['saved_digest_or_result_imported']is False and w['stat_only_validation']is False and w['live_guards_reuse_allowed']is False,'Actual complete logical byte source scope differs');rows=w['boundaries'];labels=['entry','predevice','postoperation']if ready_boundary is None else ['entry','ready','predevice','postoperation'];require([r['label']for r in rows]==labels,'Exact independent logical complete byte edges required');last=float('-inf')
 for row in rows:
  require(all(type(row[k])in (int,float)and math.isfinite(row[k])for k in ('started_epoch','finished_epoch')) and last<=row['started_epoch']<=row['finished_epoch'],'Logical complete byte chronology invalid');last=row['finished_epoch'];require(canonical(row['rows'])==canonical(epoch.evidence.initial),'Saved/current complete logical source/runtime/input bytes differ')
 seal=rows[-2];require(seal['finished_epoch']<=predevice_deadline and rows[-1]['started_epoch']>=postoperation_floor,'Logical bytes must bracket real device/terminal boundaries')
 if ready_boundary is not None:require(canonical(rows[1])==canonical(ready_boundary) and rows[1]['finished_epoch']<=ack_epoch<=seal['started_epoch'],'Actual logical READY/ACK/fresh reseal association differs')
 require(type(proof['semantic_executions'])is int and proof['semantic_executions']>0 and proof['parse_counts_complete']is True and proof['positive_parse_count']>=proof['semantic_executions'] and proof['negative_parse_count']==3*proof['positive_parse_count'],'Genuine logical successful worker counts absent')
 for row in proof['worker_commands']:
  require(row['worker_passed']is True and type(row['return_code'])is int and row['return_code']==0 and row['parse_counts']=={'positive':1,'negative':3} and row['worker_identity']['parent_pid']==owner_pid and row['worker_identity']['pid']==row['child_pid'] and row['worker_retirement']['process_terminal']is True and row['worker_retirement']['owned_session_empty']is True and row['stdout_stderr_regular_sinks_closed']is True,'Actual logical worker command/owner/terminal differs')
 worker_provenance(proof,epoch,owner_pid,case_specs,rows[0]['started_epoch'],seal['started_epoch'])
 return {'actual_logical_owner_pid':owner_pid,'complete_byte_boundaries':len(rows),'current_complete_byte_roster_rejoined':True,'live_guards_cached':False,'full_math_quality_or_serving_speed_qualified':False}

def packet_specs(epoch,specs):
 require(type(specs)is list and specs,'Explicit authenticated case specifications required');packets={};paths=set();base=dict(epoch.base_roster)
 for spec in specs:
  require(type(spec)is dict and set(spec)=={'log_path','logical_path','expected_owner_count'} and type(spec['expected_owner_count'])is int and spec['expected_owner_count']>=0,'Exact typed case specification required');log=Path(spec['log_path']);ledger=Path(spec['logical_path']);require(log.is_absolute() and ledger.is_absolute() and log==log.resolve() and ledger==ledger.resolve() and log!=ledger and log in base and ledger in base and (str(log),str(ledger))not in paths,'Unique declared current operand paths required');paths.add((str(log),str(ledger)));request={'mode':'parse','parser_source_base64':base64.b64encode(epoch.source_raw).decode('ascii'),'log_base64':base64.b64encode(epoch.evidence.bytes_for(log)).decode('ascii'),'logical_base64':base64.b64encode(epoch.evidence.bytes_for(ledger)).decode('ascii'),'require_owners':True,'expected_owner_count':spec['expected_owner_count']};packet=hashlib.sha256((canonical(request)+'\n').encode('ascii')).hexdigest();require(packet not in packets,'Duplicate worker packet across declared case inputs');packets[packet]=spec
 return packets

def command_binding(row,owner_pid,expected_command,packet,positive,lower,upper):
 require(type(row)is dict and canonical(row['command'])==canonical(expected_command) and row['input_sha256']==packet,'Exact original owned worker command/input packet differs');identity=row['worker_identity'];retired=row['worker_retirement'];require(all(type(identity[k])is int and identity[k]>0 for k in ('pid','parent_pid','start_ticks')) and type(row['child_pid'])is int and identity['pid']==row['child_pid']==retired['child_pid'] and identity['parent_pid']==owner_pid and type(retired['worker_start_ticks'])is int and retired['worker_start_ticks']==identity['start_ticks'],'Actual worker PID/start/retirement identity differs');require(type(row['return_code'])is int and row['return_code']==0 and type(retired['return_code'])is int and retired['return_code']==0 and row['error']is None and row['worker_passed']is True and canonical(row['parse_counts'])==canonical({'positive':positive,'negative':3*positive}),'Typed original worker terminal/counters differ');require(all(type(row[k])in (int,float)and math.isfinite(row[k])for k in ('started_epoch','finished_epoch')) and lower<=row['started_epoch']<=row['finished_epoch']<=upper,'Actual worker invocation chronology differs')
 for key in ('process_terminal','owned_session_empty','stdout_stderr_regular_sinks_closed','actual_worker_launched'):require(retired[key]is True,'Actual owned worker retirement missing '+key)
 require(retired['foreign_reused_session_observed']is False and retired['unexpected_descendant_rows']==[] and retired['stop_signals']==[] and retired['stdout_stderr_pipe_drain_claimed']is False,'Worker session/drain scope differs');require(row['fresh_process']is True and row['process_terminal']is True and row['stdout_stderr_regular_sinks_closed']is True and row['stdout_stderr_pipe_drain_claimed']is False and row['empty_cwd']is True and row['model_or_GPU_input']is False and canonical(row['clean_environment'])==canonical({'PATH':'/usr/bin:/bin','LANG':'C.UTF-8','LC_ALL':'C.UTF-8'}),'Actual worker execution isolation differs');require(all(type(row[k])is str and re.fullmatch('[0-9a-f]{64}',row[k])for k in ('stdout_sha256','stderr_sha256')) and row['stderr_sha256']==hashlib.sha256(b'').hexdigest(),'Original saved output byte fingerprints differ')

def worker_provenance(proof,epoch,owner_pid,specs,entry,seal):
 require(type(proof['schema'])is int and proof['schema']==1 and proof['parser_source_sha256']==PARSER_SHA and proof['worker_source_sha256']==WORKER_SHA,'Original worker/source schema differs');packets=packet_specs(epoch,specs);commands=proof['worker_commands'];require(type(commands)is list and len(commands)==len(packets),'Every declared upload packet must have one original worker');expected=[epoch.runtime['python_executable'],'-I','-B','-S',str(WORKER)];seen=set();pids=set()
 for row in commands:
  packet=row['input_sha256'];require(packet in packets and packet not in seen,'Missing/duplicate/foreign worker input packet');seen.add(packet);command_binding(row,owner_pid,expected,packet,1,entry,seal);key=(row['child_pid'],row['worker_identity']['start_ticks']);require(key not in pids,'Duplicate owned worker incarnation');pids.add(key)
 n=len(commands)
 for key,value in (('semantic_executions',n),('positive_parse_count',n),('negative_parse_count',3*n),('compact_success_tokens',n),('first_full_result_isolation_copies',n)):require(type(proof[key])is int and proof[key]==value,'Original worker/token aggregate differs '+key)
 require(type(proof['semantic_calls'])is int and proof['semantic_calls']>=n and type(proof['compact_requirement_calls'])is int and proof['compact_requirement_calls']>=n and proof['large_cached_result_exposed_by_requirement']is False,'Actual requirement/collect count scope differs');probe=proof['worker_probe_command'];probe_packet=hashlib.sha256((canonical({'mode':'probe','parser_source_base64':base64.b64encode(epoch.source_raw).decode('ascii')})+'\n').encode('ascii')).hexdigest();command_binding(probe,owner_pid,expected,probe_packet,0,0,entry)
