"""Scoped successful API accounting with independently declared placements."""
import json,math

def require(ok,msg):
 if not ok:raise ValueError(msg)
def integer(x):return type(x)is int and 0<=x<2**64
def typed(x):return json.dumps(x,sort_keys=True,separators=(',',':'),allow_nan=False)
SPACES=('device_usm','shared_usm','host_usm','host_heap')
HOST_ROLES=('host_vector_api','checkpoint_payload','conversation_payload','conversation_directory')
PLACE_KEYS={'stage','queue_context','role','role_index','layer','expert'}
def placement(row):
 require(type(row['stage'])is int and 0<=row['stage']<=1 and type(row['queue_context'])is str and row['queue_context'] and type(row['role'])is str and row['role'] and type(row['role_index'])is int and 0<=row['role_index']<256 and type(row['layer'])is int and 0<=row['layer']<48 and type(row['expert'])is int and 0<=row['expert']<512,'Exact typed actual placement fields required')
 return tuple(row[k]for k in ('stage','queue_context','role','role_index','layer','expert'))
def identity(row):return tuple(row[k]for k in ('stage','queue_context','role','role_index','owner_generation','element_size','element_count','space'))
def analyze(rows,owner,expected_placements,source_generation,expected_host_roles):
 require(type(owner)is dict and set(owner)=={'engine_pid','process_start_ticks','device_uuid','source_generation'} and type(owner['engine_pid'])is int and owner['engine_pid']>0 and integer(owner['process_start_ticks']) and type(source_generation)is int and 41<=source_generation<2**32 and type(owner['source_generation'])is int and owner['source_generation']==source_generation,'Actual future process/source owner required');host=owner['device_uuid'] is None;require(host or (type(owner['device_uuid'])is str and owner['device_uuid']),'Actual native UUID or explicit host domain required')
 require(type(expected_placements)is list and ((host and not expected_placements) or (not host and expected_placements)) and all(type(p)is dict and set(p)==PLACE_KEYS for p in expected_placements),'Exact preregistered per-placement roster required');expected={placement(p)for p in expected_placements};require(len(expected)==len(expected_placements),'Duplicate declared placement');require(type(expected_host_roles)is list and len(set(expected_host_roles))==len(expected_host_roles) and all(r in HOST_ROLES for r in expected_host_roles) and (bool(expected_host_roles)==host),'Exact host vector role roster required')
 require(type(rows)is list and 0<len(rows)<=65536,'Complete bounded original scope events required');live={};born=set();active={};seen=set();roles=set();totals={s:0 for s in SPACES};peak=dict(totals);previous=0;epoch=0
 for row in rows:
  require(typed(row['owner'])==typed(owner) and type(row['sequence'])is int and row['sequence']==previous+1,'Exact actual owner/sequential events required');previous=row['sequence'];require(type(row['host_epoch'])in (int,float) and math.isfinite(row['host_epoch']) and row['host_epoch']>=epoch,'Finite monotonic original host observations required');epoch=row['host_epoch']
  c=row['command_context'];require(type(c)is dict and set(c)=={'current_main_body_rid','actual_slot_rid','phase'} and integer(c['current_main_body_rid']) and integer(c['actual_slot_rid']) and type(c['phase'])is str and type(row['actual_slot_context_observed'])is bool and (row['actual_slot_context_observed'] or c['actual_slot_rid']==0),'Main-body and observed slot ownership remain separate');require(row['physical_residency_observed'] is False,'API accounting cannot claim physical residency')
  require(type(row['allocation_id'])is str and row['allocation_id'] and type(row['stage'])is int and (row['stage']==-1 if host else 0<=row['stage']<=1) and type(row['queue_context'])is str and row['queue_context'] and type(row['role'])is str and row['role'] and type(row['role_index'])is int and 0<=row['role_index']<256 and type(row['owner_generation'])is int and row['owner_generation']>0 and integer(row['element_size']) and integer(row['element_count']) and integer(row['bytes']) and row['bytes']>0 and integer(row['offset']),'Exact allocation/range/type/element metadata required')
  require(type(row['copy_completion_observed'])is bool and type(row['existing_completion_boundary'])is bool,'Actual completion flags must be typed booleans');kind=row['kind'];a=row['allocation_id']
  if kind=='allocation_success':
   require(a not in born and row['api_result']=='success' and row['space'] in SPACES and ((row['space']=='host_heap')==host),'Original successful backed allocation required')
   if host:require(row['role'] in expected_host_roles and row['element_size']>0 and row['element_count']>0 and row['bytes']==row['element_size']*row['element_count'],'Actual tagged host vector API extent required');roles.add(row['role'])
   else:require(row['element_size']==row['element_count']==0,'USM byte spans must not invent vector elements')
   live[a]={'identity':identity(row),'bytes':row['bytes'],'ranges':{}};born.add(a);totals[row['space']]+=row['bytes'];peak[row['space']]=max(peak[row['space']],totals[row['space']])
  elif kind=='expert_bytes_ready':
   require(not host and a in live and identity(row)==live[a]['identity'] and row['copy_completion_observed'] is True and row['existing_completion_boundary'] is True and row['completion_boundary'] in ('host_source_workers_joined','blocking_copy_wait_returned','SYCL_queued_copy_existing_wait_returned'),'Existing successful source copy boundary and exact allocation required');key=placement(row);item=live[a];require(key in expected and key not in active and row['offset']+row['bytes']<=item['bytes'],'Exact declared unborrowed placement extent required');require(all(row['offset']+row['bytes']<=offset or offset+size<=row['offset']for offset,size in item['ranges'].values()),'Overlapping ready ranges');active[key]=a;item['ranges'][key]=(row['offset'],row['bytes']);seen.add(key)
  elif kind=='expert_bytes_released':
   key=placement(row);require(a in live and active.get(key)==a and identity(row)==live[a]['identity'] and live[a]['ranges'].get(key)==(row['offset'],row['bytes']) and row['completion_boundary'] in ('owning_free_returned','overwrite_after_existing_wait'),'Exact actual placement retirement required');del active[key];del live[a]['ranges'][key]
  elif kind=='allocation_release_success':
   require(a in live and identity(row)==live[a]['identity'] and row['bytes']==live[a]['bytes'] and row['api_result']=='success' and not live[a]['ranges'],'Actual returned allocation free after range retirement required');totals[row['space']]-=live[a]['bytes'];del live[a]
  else:raise ValueError('Unknown allocation producer event')
 require(seen==expected and (not host or roles==set(expected_host_roles)),'Complete independently declared placement/host-role coverage required');require(not live and not active and not any(totals.values()),'All actual scoped owners must retire')
 return {'complete_declared_scoped_API_events':True,'peak_live_API_bytes_by_space':peak,'complete_declared_expert_placements_observed':not host,'tagged_host_vector_API_bytes_observed':host,'actual_host_cache_payload_API_bytes_observed':host and {'checkpoint_payload','conversation_payload'}<=roles,'owning_checkpoint_or_buffer_instance_observed':False,'all_host_cache_metadata_API_coverage_qualified':False,'physical_residency_qualified':False,'per_expert_physical_residency_qualified':False,'graph_consumer_retirement_independently_observed':False,'whole_process_transient_peak_qualified':False,'native_producer_runtime_qualified':False,'full_cache_goal_qualified':False}
