"""Root-only original model work; native arrays are comparison targets only."""
import hashlib,time
from pathlib import Path
import numpy as np
import owned_first_hc_fidelity_v2 as first
import full48_owned_hc_device_rs_v3 as model_module
import qualify_hc35_host_bulk_runtime_v1 as bulk
from independent_q8_1_activation_v1 import encode
from explore_owned_layer0_gdn_num10_v1 import num10_admission,load_target,FOUNDATION
from full48_owned_composition_storage_v2 import BoundOriginalFull48Rows,derive_schedule
from explore_full48_original_hc_fma_v1 import native_prefix,save_owned_and_compare
from validate_prefix_residual30_final_v4 import finalized_binding as prefix_binding
from explore_full48_original_prefix1_v4 import identity_admission,save_array,sha,read,write,require,compare_observation
class OriginalWork:
 def __init__(self,first_root,model_identity,bulk_root,prefix_root,output):
  self.first_root=Path(first_root).resolve();self.identity=Path(model_identity).resolve();self.bulk_root=Path(bulk_root).resolve();self.prefix_root=Path(prefix_root).resolve() if prefix_root else None;self.output=Path(output).resolve();self.report={'captured_inputs_used':False,'captured_states_or_routes_used':False,'ULP_adjustment_or_lookup_used':False,'full_model_math_qualified':False,'tolerance_gate':None};self.host=bulk.finalized_binding(self.bulk_root);parent,child,self.first_plan,self.first_binding=num10_admission(self.first_root);self.first_boundary=max(parent['child_terminal_epoch'],child['finished_epoch'],read(self.first_root/'post-health.json')['finished_epoch']);self.first_source=Path(self.first_plan['engine_root'])/'source';self.first_env=read(Path(self.first_plan['prepared'])/'server-config.json')['env'];self.first_source_binding=model_module.prior.source_binding(self.first_source)
  here=Path(__file__).parent;root=here.parents[1];lock=read(here/'model-lock.json');shards=[root/lock['destination']/r['path'] for r in lock['files'] if r['path'].startswith('UD-Q4_K_XL/')];self.report['original_identity_pre']=identity_admission(self.identity,here/'model-lock.json',shards,self.first_boundary);self.report['original_identity_path']=str(self.identity);self.report['host_binding']=self.host;self.report['first_native_binding']=self.first_binding;self.report['first_source_binding']=self.first_source_binding
  if self.prefix_root:
   parent,child,self.prefix_plan,self.prefix_binding=prefix_binding(self.prefix_root);self.prefix_source=Path(self.prefix_plan['engine_root'])/'source';self.prefix_env=read(Path(self.prefix_plan['prepared'])/'server-config.json')['env'];require(model_module.prior.source_binding(self.prefix_source)==self.first_source_binding,'Original first/prefix HC source contracts differ');boundary=max(parent['child_terminal_epoch'],child['finished_epoch'],self.prefix_binding['posthealth_finished']);identity_admission(self.identity,here/'model-lock.json',shards,boundary);self.report['prefix_native_binding']=self.prefix_binding
 def make_model(self,plan,env,source,device):
  provider=BoundOriginalFull48Rows(FOUNDATION,self.identity);model=model_module.OwnedHcDeviceRsReference(provider,sha(self.identity),plan['args'],env,source,self.bulk_root,device,self.output/'rs-operands');return model,provider
 def __call__(self,device):
  self.output.mkdir(parents=True,exist_ok=False);ids,targets,packets,targets_binding=load_target(self.first_root,self.first_plan,1,self.first_binding['requests']);model,provider=self.make_model(self.first_plan,self.first_env,self.first_source,device);norm_owned=np.asarray(model.projector.vector('blk.0.hc_attn_norm.weight'),dtype='<f4').reshape(4,2560);owned=first.compute_owned(model,ids);self.report['first_owned_terminal_epoch']=time.time();self.report['first_target_binding']=targets_binding;self.report['first_arrays']={'norm_owned':save_array(self.output,'first-norm-owned.f32',norm_owned)};self.report['first_comparisons']={};self.report['first_RMS_arguments']=model.owned_rms_records
  require(owned['captured_inputs_used'] is False and owned['captured_state_or_routes_used'] is False and np.asarray(targets['residual_input'],dtype='<f4').tobytes()==owned['residual_owned'].tobytes(),'Original first computation input provenance/embedding target differs')
  for name in ('embedding_owned','residual_owned'):self.report['first_arrays'][name]=save_array(self.output,'first-'+name+'.f32',owned[name])
  for name,value in owned['candidate'].items():self.report['first_arrays']['candidate_'+name]=save_array(self.output,'first-candidate-'+name+'.f32',value)
  for name,field in first.TARGET_FIELDS.items():self.report['first_comparisons'][name]=compare_observation(owned['candidate'][name],targets[field])
  packet=encode(np.asarray(owned['candidate']['mixed'],dtype='<f4').tobytes(),1,2560);p=self.output/'first-candidate-mixed.q81';p.write_bytes(packet);normalized=np.asarray(owned['candidate']['normalized'],dtype='<f4').tobytes();native_normalized=np.asarray(targets['attn_hc_normalized'],dtype='<f4').tobytes();self.report['first_gate']={'normalized_bytes_equal':normalized==native_normalized,'full_Q81_packet_bytes_equal':packet==packets['attn_input_q81'],'normalized_sha256':hashlib.sha256(normalized).hexdigest(),'native_normalized_sha256':hashlib.sha256(native_normalized).hexdigest(),'packet_sha256':sha(p),'native_packet_sha256':hashlib.sha256(packets['attn_input_q81']).hexdigest(),'passed':normalized==native_normalized and packet==packets['attn_input_q81'],'scope':'Original first HC normalized vector and complete mixed Q81 packet only'};self.report['first_device_calls']=len(device.records);require(len(device.records)==1,'Exact single own first HC RMS call required')
  self.report['prefix4_attempted']=False
  if self.prefix_root and self.report['first_gate']['passed']:
   schedule=derive_schedule(self.prefix_plan['prefixes']['4'],self.prefix_plan['args'],self.prefix_env);ids,native,nb=native_prefix(self.prefix_root,self.prefix_plan,4,schedule);prefix_model,prefix_provider=self.make_model(self.prefix_plan,self.prefix_env,self.prefix_source,device);result=prefix_model.tokens(ids);self.report['prefix4_computation_terminal_epoch']=time.time();self.report['prefix4_attempted']=True;self.report['prefix4_original_roles']={name:{'type':t['type'],'shape':t['shape_ggml_order'],'offset':t['absolute_offset'],'packed_bytes':t['packed_bytes'],'source_path':f['path'],'source_stat5':sig} for name,(f,t,sig) in prefix_provider.reader.tensors.items()};self.report['prefix4_targets']=nb;self.report['prefix4']=save_owned_and_compare(self.output,result,native);self.report['prefix4_RMS_arguments']=prefix_model.owned_rms_records;require(len(device.records)==386 and len(result['HC_device_RS_records'])==385,'Exact four-token 48-layer/HChead own RMS request roster differs')
  self.report['computation_terminal_epoch']=time.time();self.report['first_original_roles']={name:{'type':t['type'],'shape':t['shape_ggml_order'],'offset':t['absolute_offset'],'packed_bytes':t['packed_bytes'],'source_path':f['path'],'source_stat5':sig} for name,(f,t,sig) in provider.reader.tensors.items()};self.report['device_RS_records']=device.records;self.report['host_binding_post']=bulk.finalized_binding(self.bulk_root);require(self.report['host_binding_post']==self.host,'Qualified host math/helper changed');_,_,plan,binding=num10_admission(self.first_root);require(plan==self.first_plan and binding==self.first_binding,'Actual first native proof changed');require(model_module.prior.source_binding(self.first_source)==self.first_source_binding,'Original HC source changed')
  if self.prefix_root:
   _,_,plan,binding=prefix_binding(self.prefix_root);require(plan==self.prefix_plan and binding==self.prefix_binding,'Actual prefix native proof changed')
  write(self.output/'work-report.json',self.report);return self.report
 def recheck(self,report):
  from serial37_canonical_json_v3 import canonical
  require(canonical(report['original_identity_pre'])==canonical(self.report['original_identity_pre']) and report['original_identity_path']==str(self.identity) and report['host_binding']==self.host and report['first_native_binding']==self.first_binding and report['first_source_binding']==self.first_source_binding,'Original current work prerequisite changed');_,targets,packets,binding=load_target(self.first_root,self.first_plan,1,self.first_binding['requests']);require(binding==report['first_target_binding'],'Original first target source changed');gate=report['first_gate'];norm=np.frombuffer(Path(report['first_arrays']['candidate_normalized']['path']).read_bytes(),dtype='<f4').reshape(4,2560);packet=(self.output/'first-candidate-mixed.q81').read_bytes();require(gate['native_normalized_sha256']==hashlib.sha256(np.asarray(targets['attn_hc_normalized'],dtype='<f4').tobytes()).hexdigest() and gate['native_packet_sha256']==hashlib.sha256(packets['attn_input_q81']).hexdigest() and gate['normalized_bytes_equal']==(norm.tobytes()==np.asarray(targets['attn_hc_normalized'],dtype='<f4').tobytes()) and gate['full_Q81_packet_bytes_equal']==(packet==packets['attn_input_q81']) and gate['passed'] is (gate['normalized_bytes_equal'] and gate['full_Q81_packet_bytes_equal']),'Actual normalized/complete packet first gate changed');require(report['prefix4_attempted'] is (self.prefix_root is not None and gate['passed'] is True),'Requested prefix4 must follow exact first gate')
  if report['prefix4_attempted']:
   require(self.prefix_root is not None and gate['passed'] is True,'Actual prefix4 requires admitted targets and first gate');schedule=derive_schedule(self.prefix_plan['prefixes']['4'],self.prefix_plan['args'],self.prefix_env);_,native,binding=native_prefix(self.prefix_root,self.prefix_plan,4,schedule);require(binding==report['prefix4_targets'] and len(report['prefix4']['comparisons'])==577,'Exact current prefix4 target/comparison roster changed')
   for key,target in native.items():
    value=np.frombuffer(Path(report['prefix4']['arrays'][key]['path']).read_bytes(),dtype='<f4').reshape(target.shape);require(compare_observation(value,target)==report['prefix4']['comparisons'][key],'Original prefix comparison changed '+key)
  return {'first_gate_recomputed':True,'prefix4_current_577_targets_recomputed':report['prefix4_attempted'],'full_model_math_qualified':False}
