"""Exact constructor-only stat association source port; all reader math unchanged."""
from pathlib import Path
import hashlib
HERE=Path(__file__).resolve().parent
def require(ok,msg):
 if not ok:raise ValueError(msg)
def binding():
 old=(HERE/'original_gguf_reference.py').read_text();new=(HERE/'original_gguf_postboot_reference_v1.py').read_text();needle="            if r.get('passed') is not True or r['stat_before']!=r['stat_after'] or sig!=r['stat_after']:raise ValueError('Source stat/receipt changed')"
 replacement="            if r.get('passed') is not True or r['stat_before']!=r['stat_after']:raise ValueError('Original source receipt changed')\n            from postboot_original_model_association_v1 import historical_stat\n            historical_stat(model_association,p,r['stat_after'])\n            if sig!=next(row['current_stat5'] for row in model_association['mapping'] if row['path']==str(p)):raise ValueError('Current associated source stat changed')"
 require(old.count(needle)==1,'Exact old constructor guard required');expected=old.replace('class OriginalGguf:', 'class OriginalGgufPostboot:').replace('def __init__(self,manifest,identity,max_read_bytes=None):','def __init__(self,manifest,identity,max_read_bytes=None,*,model_association):').replace(needle,replacement);anchor="        self.manifest=json.loads(Path(manifest).read_bytes());m=self.manifest";insert="        from postboot_original_model_association_v1 import association as current_association\n        from serial37_canonical_json_v3 import canonical\n        fresh=current_association(identity,model_association['current_identity_path'],current_expected_sha256=model_association['current_identity_sha256'])\n        if canonical(fresh)!=canonical(model_association):raise ValueError('Exact current byte association changed')\n";expected=expected.replace(anchor,insert+anchor);require(new==expected,'Only explicit constructor stat association may change');return {'original_source_sha256':hashlib.sha256(old.encode()).hexdigest(),'new_source_sha256':hashlib.sha256(new.encode()).hexdigest(),'reader_arithmetic_or_headers_or_geometry_or_read_bounds_changed':False,'old_current_stat_gate_passed':False,'historical_snapshot_identity_SHA_retained':True}
