"""Read-only actual frontend/owner isolation and independent cold full49."""
from pathlib import Path
import live_cache_identity_controller_v2 as ctrl
from validate_live_cache_identity_v2 import finalized_binding as actor_admit
from full_cache_shared_plan_snapshot_v9 import Snapshot

def finalized_binding(root):
 root=Path(root).resolve();report=ctrl.read(root/'suite-report.json');plan=ctrl.read(root/'suite-plan.snapshot.json');ctrl.require(report['passed']is True and report['error']is None and plan['schema']=='live-identity-two-incarnation-v1'and plan['source']==report['source_after']==ctrl.source_binding(),'Actual complete source-bound identity suite required');ctrl.require(len(report['actors'])==len(plan['actors'])==2,'Both fresh independently owned native incarnations required');admitted=[];owners=[]
 for index,(saved,declared)in enumerate(zip(report['actors'],plan['actors'])):
  path=root/declared['name'];ctrl.require(saved['root']==str(path)and declared['name']=='incarnation'+str(index),'Exact actual actor path/ordering required');Snapshot(declared['plan'],declared['plan_sha256']).verify();receipt=ctrl.read(root/(declared['name']+'.receipt.json'));parent=ctrl.read(path/'parent-qualification.json');command=[receipt['command'][0],str(ctrl.HERE/'qualify_live_cache_identity_v2.py'),'--plan',declared['plan'],'--expected-plan-sha256',declared['plan_sha256'],'--output',str(path),'--leased']
  ctrl.require(receipt==saved['original_actor']and receipt['command']==command and receipt['return_code']==0 and receipt['interruption_signals']==[]and type(receipt['producer_pid'])is int and receipt['producer_pid']==parent['parent_pid']and receipt['stdout_sha256']==ctrl.sha(root/(declared['name']+'.log')),'Original suite Popen/parent/command/EOF association differs')
  value=actor_admit(path,fresh_control_roots=[Path(p)for p in saved['fresh_control_roots']]);ctrl.require(value==saved['closed_binding']and value['all_supplied_comparisons_bitwise_equal']and value['fresh_control_parent_and_source_binding_unobserved']is False,'Every actual cached/refusal/repeat/fresh49 observation required');child=ctrl.read(path/'child/report.json');ctrl.require(child['phase_receipts'][1]['work'][0]['actual_reused']==0 and child['phase_receipts'][2]['work'][0]['actual_reused']==272 and child['phase_receipts'][3]['work'][0]['actual_reused']==272,'Exact genuine cold and shared272 before/after refusal counters required');owners.append(ctrl.read(path/'child/live-identity-owner.json'));admitted.append(value)
 ctrl.require(owners[0]['namespace']==owners[1]['namespace']and report['actual_other_weights_loaded']is False,'Original locked weights only; no different-weight proof transfer');ctrl.require(ctrl.source_binding()==plan['source'],'Source changed during original suite reader')
 return {'actual_frontend_loaded_metadata_refusal_and_retirement':admitted,'actual_original_model_fresh_incarnations':2,'actual_independent_full49_cold_controls_qualified':True,'actual_alternate_native_weights_loaded':False,'supported_alternate_weight_hot_reload_endpoint':False,'native_cache_model_fingerprint_key_qualified':False,'full_cache_runtime_qualified':False,'full_model_math_qualified':False,'latency_qualified':False}
