"""Readonly new cacheOFF numerical serial supplement, actual196/full49 joins."""
from pathlib import Path
import json
import batch_serial_positive_cacheoff_v10 as ctrl
import run_batch_serial_cacheoff_v8 as adapter
from extract_serial_cacheoff_numerical_v1 import extract
from audit_batch_numerical_suite_v7 import vectors,final_source_join
from validate_batch_api_cache_positive_v2 import exact_health_gate
from batch_numerical_prefixes_v2 import compare_all
from batch_numerical_proofs_v7 import validate_artifacts

def finalized_binding(run_root):
 root=Path(run_root).resolve();parent=ctrl.read(root/'parent-qualification.json');plan=ctrl.read(root/'input-plan.snapshot.json');child=ctrl.read(root/'child/report.json');chain=ctrl.manifest_binding(plan)
 ctrl.require(parent['passed'] is True and parent['child_return_code']==0 and parent['owned_containers_terminal'] is True and parent['forced_cleanup'] is False and parent['interrupted'] is False and not parent['errors'] and parent['pre_health_passed'] is True and parent['post_health_passed'] is True and parent['kernel_fault_gate_passed'] is True,'Actual supplemental source/owned/health parent failed')
 ctrl.require(parent['scoped_collection_or_serial_arm_qualified'] is True and parent['source_guard_generation']==3,'Actual serial collection/page-watchdog scope differs')
 ctrl.require(parent['wrapper_sha256']==ctrl.sha(Path(__file__).with_name('qualify_batch_serial_positive_cacheoff_v10.py')) and parent['controller_sha256']==ctrl.sha(Path(ctrl.__file__)) and parent['prepared_chain']==chain and parent['child_report_sha256']==ctrl.sha(root/'child/report.json'),'Actual supplemental controller/parent/source identity differs')
 ctrl.require((root/'controller.py').read_bytes()==Path(ctrl.__file__).read_bytes() and (root/'wrapper.py').read_bytes()==Path(__file__).with_name('qualify_batch_serial_positive_cacheoff_v10.py').read_bytes(),'Actual serial producer source snapshots differ')
 cli=ctrl.read(root/'child.command.json');ctrl.require(Path(cli[0]).resolve()==Path(child['producer_interpreter']).resolve() and ctrl.sha(Path(child['producer_interpreter']))==child['producer_interpreter_sha256'] and cli[1:]==[str(Path(ctrl.__file__)), 'run','--plan',str(Path(parent['plan']).resolve()),'--pre-health',str(root/'pre-health.json'),'--output',str(root/'child')] and child['producer_pid']==parent['child_pid'],'Actual serial child CLI/interpreter/PID association differs')
 ctrl.require(child['schema']==7 and child['harness_generation']==10 and child['serial_positive_generation']==10 and 'plan_sha256' in child and child['plan_sha256']==ctrl.sha(root/'child/plan.snapshot.json'),'Future explicit producer child snapshot SHA absent/wrong');ctrl.require(child['collection_and_teardown_passed'] is True and child['passed'] is True and child['cache_qualification_granted'] is False and child['actual_cached_state_handoff_qualified'] is False and child['full_model_math_qualified'] is False,'Actual numerical supplement collection absent/scope differs');validate_artifacts(root/'child',child['artifact_bindings']);source=final_source_join(root,parent,plan,child)
 for stage in ('pre','post'):exact_health_gate(root,stage)
 collector=Path(plan['batch_parent']);_,_,_,collector_proof,batch=ctrl.collector_binding(collector);jobs=ctrl.read(collector/'child/serial-jobs.json')['jobs'][plan['group_index']*6:plan['group_index']*6+6];directory=root/'child'/('serial-'+str(plan['group_index']));terminal=ctrl.read(directory/'result.json');ctrl.require(terminal['passed'] is True and terminal['engine_rc']==0 and terminal['removed'] is True and terminal['state']['ExitCode']==0 and not terminal['state']['Running'] and not terminal['state']['OOMKilled'] and terminal['error'] is None,'Actual numerical native process terminal differs');ctrl.require(ctrl.read(directory/'command.json')==adapter.command_recipe(plan,root/'child',plan['group_index'],parent['child_pid']),'Actual numerical serial fullcommand recipe differs');rows=ctrl.read(directory/'requests.json');ctrl.require(len(rows)==len(jobs)==plan['serial_group_job_count'],'Actual supplemental serial selected jobcount differs');args,env=adapter.config(plan);serial={}
 for row,job in zip(rows,jobs):
  ctrl.require(row['job']==job and row['raw']['ids']==job['ids'],'Actual consumed-prefix serial job differs');rawpath=directory/('serial-'+str(job['rid'])+'-'+job['role']+'.json');ctrl.require(ctrl.read(rawpath)==row['raw'],'Actual individual GEN source record changed');new=extract(row['raw'],directory/'captures',args,env,ctrl.expected_stage_ranges(args));ctrl.require(json.loads(json.dumps(new))==row['meta'],'CacheOFF numerical raw/lifecycle recollection differs');key=(job['rid'],job['role']);serial[key,-1]=new['logits'][0]['path']
  for f in new['residuals']:serial[key,int(f['layer'])]=f['path']
 result=compare_all({k:v for k,v in batch.items() if k in serial},serial);ctrl.require(result['passed'] is True,'Actual full49 serial/batch bytes differ');stored=ctrl.read(root/'child/serial-comparison.json');ctrl.require(result['comparisons']==stored['comparisons']==child['comparisons'] and len(serial)==49*len(jobs),'Actual stored full49 comparison differs')
 ctrl.require(child['actual_serial_job_count']==len(jobs) and child['actual_matched_full49_vector_pairs']==len(serial),'Future producer actual copycounts differ');source_after=final_source_join(root,parent,plan,child);ctrl.require(ctrl.manifest_binding(plan)==chain,'Actual supplemental current proof changed after raw comparison');return parent,child,plan,{'actual_positive_collector_proof':collector_proof,'actual_positive_handoff_full49_control_groups_complete':False,'matched_vector_pairs':len(serial),'actual_consumed_prefix_jobs':len(jobs),'all_raw_pairs_bitwise_equal':True,'cache_qualification_granted':False,'full_model_math_qualified':False,'source_before':source,'source_after':source_after}

def all_groups_binding(collector_root,serial_roots):
 """Join every actual fresh group; no fullcache/model/speed qualification."""
 collector=Path(collector_root).resolve();_,source,_,collector_proof,batch=ctrl.collector_binding(collector);jobs=ctrl.read(collector/'child/serial-jobs.json')['jobs'];required=set(range((len(jobs)+5)//6));seen=set();pairs=0;reports=[]
 ctrl.require(any(j['role']=='solo_migration' for j in jobs),'Actual solo migration consumed-prefix job required in complete controls')
 for directory in serial_roots:
  p,c,q,binding=finalized_binding(directory);group=q['group_index'];ctrl.require(Path(q['batch_parent']).resolve()==collector and group in required and group not in seen and q['collector_plan_sha256']==ctrl.sha(collector/'input-plan.snapshot.json'),'Every unique actual source-bound control group required');seen.add(group);pairs+=binding['matched_vector_pairs'];reports.append({'directory':str(Path(directory).resolve()),'group':group,'report_sha256':ctrl.sha(Path(directory)/'child/report.json'),'matched_vector_pairs':binding['matched_vector_pairs']})
 ctrl.require(seen==required and pairs==49*len(jobs)==len(batch),'All actual source job full49 controls mustclose; partialgroups notqualified');ctrl.collector_binding(collector)
 return {'actual_positive_collector_proof':collector_proof,'all_actual_source_consumed_prefix_jobs':len(jobs),'all_full49_bitwise_fresh_controls_passed':True,'matched_vector_pairs':pairs,'groups':reports,'actual_cached_state_handoff_qualified':False,'cache_qualification_granted':False,'full_model_math_qualified':False,'latency_qualified':False,'scope':'actual positive source records + complete freshcacheOFF head/all48 numeric controls; matchedOFF/ON/concurrency/fullcache gates remain separate'}
