#!/usr/bin/env bash
# Research launcher that transplants the qualified FP8 MTP1 runtime shape onto
# the Qwen3.8-27B compressed-tensors W8A8 checkpoint.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../../.." && pwd)"
PROFILE="${PROFILE:-control}"

case "$PROFILE" in
  control)
    export SPECULATIVE_TOKENS="${SPECULATIVE_TOKENS:-0}"
    export P2P_ACCESS="${P2P_ACCESS:-0}"
    export XPU_GRAPH="${XPU_GRAPH:-0}"
    export CUDAGRAPH_MODE="${CUDAGRAPH_MODE:-FULL_DECODE_ONLY}"
    export MAX_MODEL_LEN="${MAX_MODEL_LEN:-8192}"
    export MAX_NUM_SEQS="${MAX_NUM_SEQS:-1}"
    export MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-8192}"
    export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.90}"
    export INT8_INPUT_DEPENDENCY="${INT8_INPUT_DEPENDENCY:-1}"
    ;;
  target_full)
    export SPECULATIVE_TOKENS="${SPECULATIVE_TOKENS:-0}"
    export P2P_ACCESS="${P2P_ACCESS:-1}"
    export XPU_GRAPH="${XPU_GRAPH:-1}"
    export CUDAGRAPH_MODE="${CUDAGRAPH_MODE:-FULL_DECODE_ONLY}"
    export MAX_MODEL_LEN="${MAX_MODEL_LEN:-237568}"
    export MAX_NUM_SEQS="${MAX_NUM_SEQS:-4}"
    export MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-32768}"
    export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.96}"
    export INT8_INPUT_DEPENDENCY="${INT8_INPUT_DEPENDENCY:-0}"
    ;;
  mtp1_diagnostic)
    export SPECULATIVE_TOKENS="${SPECULATIVE_TOKENS:-1}"
    export P2P_ACCESS="${P2P_ACCESS:-1}"
    export XPU_GRAPH="${XPU_GRAPH:-1}"
    export CUDAGRAPH_MODE="${CUDAGRAPH_MODE:-FULL_DECODE_ONLY}"
    export MAX_MODEL_LEN="${MAX_MODEL_LEN:-237568}"
    export MAX_NUM_SEQS="${MAX_NUM_SEQS:-4}"
    export MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-32768}"
    export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.96}"
    export INT8_INPUT_DEPENDENCY="${INT8_INPUT_DEPENDENCY:-1}"
    ;;
  *)
    echo "PROFILE must be control, target_full, or mtp1_diagnostic" >&2
    exit 2
    ;;
esac

graph_id=eager
if [ "$XPU_GRAPH" -eq 1 ]; then
  graph_id="${CUDAGRAPH_MODE,,}"
fi
PROFILE_ID="mtp${SPECULATIVE_TOKENS}-p2p${P2P_ACCESS}-${graph_id}-ctx${MAX_MODEL_LEN}"

export IMAGE="${IMAGE:-b70-local/vllm-openai-xpu:qwen38-w8a8-int8-mtp1-r03}"
export EXPECTED_IMAGE_ID="${EXPECTED_IMAGE_ID:-sha256:5dad53a3ef34f6615ab35e7ea984ca6062d48c4c7e3050c07f74d49091948639}"
export MODEL_DIR="${MODEL_DIR:-$REPO/models/files/qwen3.8-27b/w8a8-gptq}"
export CACHE_DIR="${CACHE_DIR:-/mnt/vm_8tb/b70/cache/qwen38-w8a8-int8-${PROFILE_ID}}"
export NAME="${NAME:-qwen38_w8a8_int8_${PROFILE}}"
export PORT="${PORT:-18080}"
export SERVED="${SERVED:-qwen3.8-27b-W8A8-gptq-native-int8-${PROFILE_ID}}"
export QUANTIZATION=compressed-tensors
export PYTHONPATH_OVERLAY=/opt/b70-qwen38-w8a8
export FP8_BLOCK_W8A16=0
export INT8_COMPLETION_BARRIER="${INT8_COMPLETION_BARRIER:-0}"
export INT8_SCRATCHPAD_RING_SIZE="${INT8_SCRATCHPAD_RING_SIZE:-1}"
export INT8_QUANT_MAX_LOCAL="${INT8_QUANT_MAX_LOCAL:-256}"
export INT8_NATIVE_QUANT="${INT8_NATIVE_QUANT:-0}"
export LAYERNORM_SHA256="${LAYERNORM_SHA256:-d911627c6c8f16fc11e02846286c378220120d24bd75898a5337fadf459318bd}"
export RMS_PACKED_SERIAL_EXACT="${RMS_PACKED_SERIAL_EXACT:-1}"
export GDN_PERSISTENT_SCRATCH="${GDN_PERSISTENT_SCRATCH:-1}"
export COMPILATION_PROFILE="${COMPILATION_PROFILE:-publisher}"
export ATTENTION_BACKEND="${ATTENTION_BACKEND:-TRITON_ATTN}"
if [ "$SPECULATIVE_TOKENS" -gt 0 ]; then
  export DRAFT_ATTENTION_BACKEND="${DRAFT_ATTENTION_BACKEND:-TRITON_ATTN}"
else
  export DRAFT_ATTENTION_BACKEND="${DRAFT_ATTENTION_BACKEND:-}"
fi
export FORCE_GRAPH_WITH_COMM="${FORCE_GRAPH_WITH_COMM:-1}"
export USE_V2_MODEL_RUNNER="${USE_V2_MODEL_RUNNER:-0}"
export ALLOW_EXISTING_CACHE="${ALLOW_EXISTING_CACHE:-1}"
export INDUCTOR_COMBO_KERNELS="${INDUCTOR_COMBO_KERNELS:-0}"
export INDUCTOR_BENCHMARK_COMBO_KERNEL="${INDUCTOR_BENCHMARK_COMBO_KERNEL:-0}"
export INDUCTOR_MAX_AUTOTUNE="${INDUCTOR_MAX_AUTOTUNE:-0}"
export INDUCTOR_COORDINATE_DESCENT_TUNING="${INDUCTOR_COORDINATE_DESCENT_TUNING:-0}"
export INDUCTOR_AUTOTUNE_POINTWISE="${INDUCTOR_AUTOTUNE_POINTWISE:-0}"
export INDUCTOR_DETERMINISTIC_CONFIG="${INDUCTOR_DETERMINISTIC_CONFIG:-1}"

if [ "$P2P_ACCESS" -eq 1 ]; then
  export I_KNOW_P2P_WEDGES=1
fi

exec "$REPO/vllm/fp8/serve_qwen38_fp8_neural_f02.sh" "$@"
